### ISSUE TITLE
samtool depth reports unexpected values

### ISSUE THREAD

**Issue by bernt-matthias** [samtools/samtools#889] opened 2018-07-10 12:17 UTC
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

1.8

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)

Linux 4.4.0-130-generic
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

`samtools depth -d 3 eboVir3.bam`

the file can be downloaded here: https://github.com/bernt-matthias/tools-iuc/blob/f686ef690b2e932e40acb3fd38bb9a00dd0ec911/tool_collections/samtools/samtools_depth/test-data/eboVir3.bam?raw=true

According to the documentation I do not expect depth values > 3, but there are. Could you please clarify this?

**Comment by peterjc** [comment] 2018-07-10 12:41
I noticed a certain fuzziness while writing this tool which was tested on ultra-high coverage viral data:

https://github.com/peterjc/pico_galaxy/blob/master/tools/coverage_stats/coverage_stats.py

I concluded the limit was applied at read level, not mapped base level, but rather than solving exactly what samtools was doing and trying to fix it, I took a pragmatic way out - I told samtools to use the desired max-depth plus a margin, and then applied the desired max-depth in post-processing.

**Comment by jkbonfield** [comment] 2018-07-10 13:46
The depth limit is there to prevent excessive memory usage in extremely deep locations.  It is not a cast iron guarantee of precise maximum depth.  I haven't checked the code in detail, but my expectation is this is likely caused by a naive depth filtering that doesn't take into account the full nuances of how CIGAR strings can change read sizes slightly.

**Comment by bernt-matthias** [comment] 2018-07-10 14:17
Then I guess the following questions should to be answered in the documentation: 

- What is actually counted (ie in which cases is read counted for a base)
- Are the results of the program exact with `-d 0`? 
- How does -d !=0 affect the counts?

**Comment by peterjc** [comment] 2018-07-11 13:21
@jkbonfield that's what I concluded, e.g. regions with lots of CIGAR delete operators might really exceed the specified max-depth, but their coverage can be under-reported depending on the reads sampled.

I don't have an explanation for exceeding the max-coverage, but perhaps CIGAR inserts are involved? As Bernt says, from the user facing documentation exactly what is counted is unclear.

**Comment by jkbonfield** [comment] 2018-07-11 16:57
Actually it's weirder than this.  The depth field applies to the maximum number of sequences *starting* at any point.  So with -d 1 we cannot have two reads that start in the same location.  We can however have two reads starting 1bp apart, which then leads to higher depth.

This was presumably written in an era of short reads where the depth limit is considered simply a workaround for huge piles of reads aligned in the same location (eg all those poly-As!).  It's not particularly sensible for long reads.

However making it a depth limit for any overlapping read is hard to get right.  Eg consider 10M at pos 1 and 10M at pos 5.  If we filter the 10M at pos 5 because it overlaps the read starting at pos 1, then we don't have any depth from 10 to 14, which we would do had we allowed depth 2.  Thus that scenario would cause coverage holes to appear immediately after any overly deep region.  The method of having a maximum count starting at a single location works around that problem.

How on earth to describe this?  I think perhaps it just needs documenting in terms of an efficiency thing and not as a hard limit forbidding greater depth.

**Comment by jkbonfield** [comment] 2018-07-11 17:06
Note @daviesrob has already modified the documentation for the `samtools mpileup -d` option with the following:

                 -d, --max-depth INT
                           At  a  position, read maximally INT reads per input file. Setting this limit
                           reduces the amount of memory and time needed to process  regions  with  very
                           high coverage.  Passing zero for this option sets it to the highest possible
                           value, effectively removing the depth limit. [8000]

                           Note that up to release 1.8, samtools would enforce a minimum value for this
                           option.  This no longer happens and the limit is set exactly as specified.

This text could be added to the `samtools depth` part of the manual page too.

This also answers your other question regarding depth of 0.

**Comment by valeriuo** [comment] 2021-06-28 13:26
Fixed by #1428

**Closed by valeriuo** 2021-06-28 13:26 UTC
