### ISSUE TITLE
Multi-region iterator does not work with remote files

### ISSUE THREAD

**Issue by andras86** [samtools/samtools#1071] opened 2019-07-03 15:58 UTC
I'm using samtools 1.9.

If I run `samtools view` on a remote (ftp) cram file with regions specified, I get the expected results as long as I provide the regions in the command line. Clearly it finds the remote `.cram.crai` file sitting next to the `.cram` address that I pass, because it works and runs through quickly.

However, if I pass the regions as a bed file with the `-M my_regions.bed` option, I get the error
```
[E::idx_find_and_load] Could not retrieve index file for 'my_regions.bed'
[main_samview] random alignment retrieval only works for indexed BAM or CRAM files.
```
suggesting that it doesn't find the index in this case.

I dug around and found that there is a new option `-X` in the develop branch that allows the user to pass the index file explicitly, so I built the develop version, but it still doesn't work, regardless of whether I pass the ftp address of the `.cram.crai` file, or download it and pass it as a local file. I still get the same `[main_samview] random alignment retrieval only works for indexed BAM or CRAM files` error.

Any help or workaround appreciated!
Andras

**Comment by valeriuo** [comment] 2019-07-03 16:15
Duplicate of #972

**Comment by valeriuo** [comment] 2019-07-03 16:17
Try `samtools view -ML my_regions.bed ...`

**Closed by valeriuo** 2019-07-03 16:17 UTC
