### ISSUE TITLE
samtools index error

### ISSUE THREAD

**Issue by ccmeth** [samtools/samtools#1832] opened 2023-04-19 03:02 UTC
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
samtools 1.12
Using htslib 1.12
 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)
Linux 5.4.0-146-generic
#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
I used the bowtie2 to map fastq to fly genome.
Then I samtools index *.bam and I only got the error "samtools index: failed to create index for *.bam: numerical result out of range".
Such an error seems to be a littte strange since other bugs other people showed contained location information.
Besides, samtools sort *.bam > *.1.bam report the error: samtools sort: truncated file. Aborting.

**Comment by whitwham** [comment] 2023-04-19 09:27
You are not getting a location because "numerical result out of range" is probably happening at a lower level than samtools.

I am a bit suspicious of the use of wildcards here.  Try using the actual file names and see what happens.

**Comment by ccmeth** [comment] 2023-04-19 10:24
> You are not getting a location because "numerical result out of range" is probably happening at a lower level than samtools.
> 
> I am a bit suspicious of the use of wildcards here. Try using the actual file names and see what happens.

Thanks for your reply and sorry for my presentation. The error is displayed below. 
![image](https://user-images.githubusercontent.com/54224100/233046397-f81bc443-d573-45ec-bfb5-78e0f7e17987.png)

**Comment by whitwham** [comment] 2023-04-19 10:35
Okay, it looks like the bam file is corrupted in some way.

You could try `samtools quickcheck tmp_exogenous.bam` to see if it passes that.  If that works try `samtools head tmp_exogenous.bam` to see if you can extract any header information.

**Comment by ccmeth** [comment] 2023-04-19 11:42
> Okay, it looks like the bam file is corrupted in some way.
> 
> You could try `samtools quickcheck tmp_exogenous.bam` to see if it passes that. If that works try `samtools head tmp_exogenous.bam` to see if you can extract any header information.

samtools quickcheck indicated that this bam file is well, besides, "samtools view -H  tmp_exogenous.bam" > header.txt also worked well. 
![image](https://user-images.githubusercontent.com/54224100/233063929-2beaeb32-6af2-4932-9b1e-493f47b9f02b.png)
[header.txt](https://github.com/samtools/samtools/files/11272554/header.txt)

**Comment by ccmeth** [comment] 2023-04-19 11:53
Besides, this header was compared with another bam files which could be indexed smoothly, and these two header files are quite same.

**Comment by whitwham** [comment] 2023-04-19 13:02
The point of my questions is to try to find where the error is.  The `quickcheck` shows that the basic structure is okay and writing the header indicates that the header is also intact.

The "numerical result out of range" error message is for the ERANGE error which is set in a few places where the contents of the bam record does not match what is expected.  This could be caused by bad encoding into bam or file corruption.

So somewhere in the read data something is wrong.  One of the causes other people have had is piping the error logging from the aligner into the bam file.  That maybe something you want to check.  You could also trying writing the file out as sam and seeing how far it gets before failing.

**Comment by ccmeth** [comment] 2023-04-20 01:46
Based on your suggestions, I did "samtools view tmp_exogenous.bam" and "samtools view tmp_exogenous.bam > tmp_exogenous.sam", both showed error: samtools view: error reading file "tmp_exogenous.bam": numerical result out of range. However, when contents in bam was exhibited to screen, I noticed one phenomenon shown below.

![image](https://user-images.githubusercontent.com/54224100/233236568-02904c90-347e-47c8-8788-ebbc18950329.png)
Is this responsible for this error?

**Comment by jmarshall** [comment] 2023-04-20 02:24
Because your version of samtools predates PR #1490 (which appeared in v1.14), the error message appears embedded in the data a few lines before the end of the output, but this is just an artefact.

What this message is telling you is that the problem is in the first unshown record, i.e., the next record after the second SRR12813523.1104032 one — which will be somewhere in the middle of your BAM file, not necessarily towards the end.

Hopefully there is a way to have bowtie keep a copy of the SAM file before converting it to BAM, so that you can look for that record. Or you could see what messages Picard gives on your BAM file. Or there are more difficult ways to decode the binary BAM structure by hand to see what is wrong with that record.

**Comment by whitwham** [comment] 2023-04-26 11:42
Is there any update?

**Comment by whitwham** [comment] 2023-05-02 14:17
No updates, closing issue.

**Closed by whitwham** 2023-05-02 14:17 UTC
