### ISSUE TITLE
empty values and unaccounted begins and ends of reads in mpileup file

### ISSUE THREAD

**Issue by vttrifonov** [samtools/samtools#385] opened 2015-05-06 17:20 UTC
I have a mpilueup file which has some empty value. See that circled area in the image below

![image](https://cloud.githubusercontent.com/assets/12157034/7498833/8a8cbcf6-f3d8-11e4-9d47-46bac68f350b.png)

What is the meaning of this? As you can see the next position has some "unaccounted" reads, which are are marked to exist (the 16 commas) but do not begin in the previous line. Same column ends with a read that has an unaccounted for ending (see the circled area in the image below)

![image](https://cloud.githubusercontent.com/assets/12157034/7498937/42729836-f3d9-11e4-8f8b-f95bac774b0e.png)

**Comment by jkbonfield** [comment] 2015-05-18 08:50
Sorry for the slow reply on this.  Thanks for the bug report.

What is your exact command you are running here? Is it possible that these reads may exist but be having their bases filtered out due to a quality setting, or due to BAQ realignment?  Does using -A and -B options bring them back?

I am also a little bit unsure of what I am seeing in these images as they aren't vanilla mpileup output.  I assume it is still the case that each row is from the next sequential reference base, but with no coordinates shown.  No output at all (not even "*") seems wrong though.

Is is possible to provide us with a SAM snippet that demonstrates this bug, please?  I'll take a look through the code and see if I can find any code paths that would trigger this behaviour.

**Comment by jkbonfield** [comment] 2015-05-18 09:04
Ah, I've found one case of triggering this.  It's an oddity of the BAQ alignment code, which frankly I'm out of my depth to address!

Consider the following example:

```
@SQ     SN:c1   LN:10
s0a     0       c1      1       0       10M     *       0       0       AACCGCGGTT      """""IIIII
```

So it has 5 bases of Q2 and 5 of Q-something-high.

mpileup -Q 1 shows:

```
c1      1       N       1       ^!A     "
c1      2       N       1       A       "
c1      3       N       1       C       "
c1      4       N       1       C       "
c1      5       N       1       G       "
c1      6       N       1       C       I
c1      7       N       1       G       I
c1      8       N       1       G       I
c1      9       N       1       T       I
c1      10      N       1       T$      I
```

mpileup -Q 2 shows:

```
c1      1       N       0
c1      2       N       0
c1      3       N       0
c1      4       N       0
c1      5       N       0
c1      6       N       1       C       I
c1      7       N       1       G       I
c1      8       N       1       G       I
c1      9       N       1       T       I
c1      10      N       1       T$      I
```

The bases have been deliberately filtered out as per the -Q parameter "skip bases with baseQ/BAQ smaller than INT [13]".  This is working as intended.

However I am unsure what it should do regarding read start characters.  Technically the read does not start at pos 6 so we wouldn't expect a ^!C to be there, but you could make an argument for base quality filtering being equivalent to a soft-clip if it occurs at the end.  Unfortunately it can also occur in the middle and that leads to similar oddities. Eg quality string ""II""II"" yields:

```
c1      1       N       0
c1      2       N       0
c1      3       N       1       C       I
c1      4       N       1       C       I
c1      5       N       0
c1      6       N       0
c1      7       N       1       G       I
c1      8       N       1       G       I
c1      9       N       0
c1      10      N       0
```

Even if we edited the algorithm to show ^ and $ for the first and last used bases, we'd also have to add extra ones for the internal gap too.  I think it's simply not designed to do this and so isn't a bug, but by design.

Heng or Petr care to comment on this interpretation?

**Comment by jkbonfield** [comment] 2015-05-26 15:12
Closing in absence of any further discussions.

**Closed by jkbonfield** 2015-05-26 15:12 UTC
