### ISSUE TITLE
error: Could not realloc buffers, the sequence too long:

### ISSUE THREAD

**Issue by thsyd** [samtools/samtools#1000] opened 2019-01-22 13:42 UTC
Hi,
trying to use samtools stats to get the error rate of a bacterial genome assembly (compared to a reference).
Inspired by 
https://github.com/nataliering/Resolving-the-complex-Bordetella-pertussis-genome-using-barcoded-nanopore-sequencing/blob/master/raw_error

The reference genome is two contigs (aprox 5.2mb and 32000b).
The assembly is the same (hydrid from nanopore and illumina reads).

Using minimap2 to allign
```
minimap2 -t 8 -a $ref_genome assembly.fasta | samtools sort -@ 8 -o assembly.minimap2.sorted.bam
samtools stats assembly.minimap2.sorted.bam > assembly.minimap2.sorted.bam.stats
```
outputs the error:
> Could not realloc buffers, the sequence too long: 5221902 (-12971438080)

I get the same error if I allign with bwa mem -x ont2d
I do not get the error if I allign another assembly (skesa) assembled just with the illumina data.

suggestions?

**Comment by jkbonfield** [comment] 2019-01-22 17:02
The problem here is you have an individual sequence that is huge, which stats was never designed to cope with.  It is overflowing the "int" data type.  The above error is all over the place, but the one it appears to hit first is https://github.com/samtools/samtools/blob/develop/stats.c#L631

```
stats->mpc_buf = realloc(stats->mpc_buf, n*stats->nquals*sizeof(uint64_t));
if ( !stats->mpc_buf )
    error("Could not realloc buffers, the sequence too long: %d (%ld)\n", seq_len,n*stats->nquals*sizeof(uint64_t));
```
Here n is seq length*2 (more or less), nquals is 256, so the entire thing becomes huge, bigger than 32-bit in size.

We can get around most of these issues by just changing the multipliers to be 64-bit so all expressions become 64-bit, eg nquals and nbases in struct stats_t.  However it isn't sufficient by itself as there are various other bits such as line 617:

```
    int n = 2*(1 + seq_len - stats->nbases) + stats->nbases;
```

Fact is, you're hosed frankly anyway.  Even fixing these, stats will be very slow and use 50+Gb of memory, maybe even 100s of Gb (I stopped it at 50Gb as that was the limit of the system I was on).

What is it you're trying to achieve?

**Comment by jamesdalg** [comment] 2024-02-21 16:50
I wish to add that this is happening on multiple fa files in version 1.19.2. I have never seen this before and I'm just using hg38.fa

**Comment by jkbonfield** [comment] 2024-02-21 17:02
Can you confirm that the exact same samtools command line with an earlier version of samtools isn't using so much memory up?  If so then this is indeed a regression and we should be able to bisect things until we find the offending commit (assuming we can reproduce the problem)

**Comment by jamesdalg** [comment] 2024-02-21 18:26
Here's a reprex. I get the exact same error on 1.19.2. Both are running ubuntu. One of the machines has 1.5TB of ram and doesn't run out.
(base) jd@acadia:~$ wget https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz --compress=auto
--2024-02-21 18:19:37--  https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz
Resolving hgdownload.soe.ucsc.edu (hgdownload.soe.ucsc.edu)... 128.114.198.53
Connecting to hgdownload.soe.ucsc.edu (hgdownload.soe.ucsc.edu)|128.114.198.53|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 983659424 (938M) [application/x-gzip]
Saving to: ‘hg38.fa.gz’

hg38.fa.gz          100%[===================>] 938.09M  18.6MB/s    in 54s     

2024-02-21 18:20:32 (17.2 MB/s) - ‘hg38.fa.gz’ saved [983659424/983659424]

(base) jd@acadia:~$ gunzip hg38.fa.gz 
(base) jd@acadia:~$ samtools stats hg38.fa 
Could not realloc buffers, the sequence too long: 248956422 (-11067256832)
(base) jd@acadia:~$ samtools --version
samtools 1.13
Using htslib 1.13+ds
Copyright (C) 2021 Genome Research Ltd.

Samtools compilation details:
    Features:       build=configure curses=yes 
    CC:             gcc
    CPPFLAGS:       -frelease  -Wdate-time -D_FORTIFY_SOURCE=2
    CFLAGS:         -g -O2 -ffile-prefix-map=�BUILDPATH�=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security
    LDFLAGS:        -Wl,-Bsymbolic-functions -flto=auto -Wl,-z,relro -Wl,-z,now
    HTSDIR:         
    LIBS:           
    CURSES_LIB:     -lcurses

HTSlib compilation details:
    Features:       build=configure plugins=yes, plugin-path=/usr/local/lib/htslib:/usr/local/libexec/htslib:: libcurl=yes S3=yes GCS=yes libdeflate=yes lzma=yes bzip2=yes htscodecs=1.1.1
    CC:             gcc
    CPPFLAGS:       -I. -DSAMTOOLS=1 -Wdate-time -D_FORTIFY_SOURCE=2
    CFLAGS:         -g -O2 -ffile-prefix-map=/build/htslib-TQtOKr/htslib-1.13+ds=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -flto -fvisibility=hidden -flto -fvisibility=hidden
    LDFLAGS:        -Wl,-Bsymbolic-functions -flto=auto -Wl,-z,relro -Wl,-z,now -Wl,-flto -fvisibility=hidden -Wl,-flto -fvisibility=hidden

HTSlib URL scheme handlers present:
    built-in:	 preload, data, file
    crypt4gh-needed:	 crypt4gh
    mem:	 mem
```

**Comment by jkbonfield** [comment] 2024-02-22 09:08
> (base) jd@acadia:~$ samtools stats hg38.fa 
> Could not realloc buffers, the sequence too long: 248956422 (-11067256832)

Possibly it ought to work, but this is very much not what samtools was intended for!  It's meant to process reads aligned against a genome, not treating the genome itself as reads.  As yet the longest read ever produced was a couple MB, and they're vanishingly rare and only possible with specific protocols.  Normally ONT is going to max out well under a MB.

I'm not sure what it is you're attempting to do here.  Do you have genuine sequenced DNA which is triggering this issue?

Also you mentioned this didn't happen in earlier releases.  Which releases?  I tried 1.13 and it has exactly the same error.

So I don't believe this is a regression at all, just that it cannot do something (that we didn't intend for it to do).

**Comment by daviesrob** [comment] 2024-02-22 09:10
You're trying to run `samtools stats` on a reference sequence.  It's not designed for that sort of input, and wouldn't really show you anything useful.  It should instead by run on files containing sequencing reads aligned against the reference.

Usually the input would be a sam, bam or cram file, not fasta.

**Comment by jkbonfield** [comment] 2024-02-22 09:21
Actually looking above, I see this is just a trivial example to reproduce the error, but not the command that initially produced it.

> samtools stats assembly.minimap2.sorted.bam > assembly.minimap2.sorted.bam.stats
> 
> outputs the error:
>    Could not realloc buffers, the sequence too long: 5221902 (-12971438080)

The error comes from here https://github.com/samtools/samtools/blob/develop/stats.c#L633-L713
I'm unsure which line exactly as they all have the same confusing error message.

Stats does use a lot of memory up as it has large rectangular arrays of length x num_qual x 64-bit.  Even so it shouldn't be erroring out that quick.  (Also do you *really* have a 5MB+ long alignment?)

Are you running in a memory constrained environment?  Eg does ulimit -a give you hints on the maximum memory you're allowed to use?

**Comment by jkbonfield** [comment] 2024-02-22 09:43
Closing this as I see the issue is an ancient one.  Some estimations locally shows that while samtools stats is quite frankly excessive in the memory usage for long read technologies, even the mammoth 5MB read the original poster had would still only be using 20GB of RAM up to complete samtools stats.  Wasteful, but not impossible to achieve on big hardware.

Really there's a different issue, better tracked elsewhere.  `samtools stats` is pretty worthless on long-read technologies and needs a total rethink.

**Closed by jkbonfield** 2024-02-22 09:43 UTC
