### ISSUE TITLE
@GR and @PG is missing 

### ISSUE THREAD

**Issue by harryzs** [samtools/samtools#430] opened 2015-07-10 14:42 UTC
Just find it is duplicate....#411 #416......Sorry.

------------------------------------------------
Dear all,

Version: samtools-1.2

I have on bam file (for example: A.bam) with @RG and @PG in header.

I run: 
-------------------
samtools view -b A.bam | samtools sort - sorted

[bam_sort_core] merging from 3 files...
-------------------

Then,  I got sorted.bam but @RG and @PG is missing from the header of sorted.bam.

I tried samtools-1.1, everyone is fine.

Regards,
Sheng

**Comment by jmarshall** [comment] 2015-07-11 00:38
Duplicate of #411.

**Closed by jmarshall** 2015-07-11 00:38 UTC
Labels: duplicate

**Comment by mp15** [comment] 2015-07-28 15:31
Fixed by 227c142c288b4757e9bd7907a0b52a9f16ee451b
