### ISSUE TITLE
samtools idxstats shows zero reads

### ISSUE THREAD

**Issue by sarawernig** [samtools/samtools#800] opened 2018-03-19 16:30 UTC
I need a read count per chromosome and I'm using samtools idxstats. I get zero aligned and zero unaligned reads as output. Although I definitely have 12 million aligned reads according to bowtie2 and samtools flagstat. I tried using 2 different versions of samtools and bamtools, but no difference. Any clue what is happening? I need this information for downstream processing.

**Comment by daviesrob** [comment] 2018-03-20 16:47
Were you trying to use this on a cram file?

Unfortunately the information needed for some of the data idxstats reports is not available in the cram index format so some of the output will be missing on cram files.

**Comment by valeriuo** [comment] 2018-04-26 10:03
Relaying to #303

**Comment by swernig** [comment] 2018-04-26 10:25
It's not relaying to #303, because it wasn't a CRAM file. So i don't understand why you closed this issue since it remains unsolved.

**Comment by jkbonfield** [comment] 2018-04-26 10:45
You didn't answer the previous query so we just assumed.  What format is the file?  Does it have an index?  If you have a bug with an indexed BAM then this is indeed a problem, but we'd need more information to work on and ideally a test file demonstrating the problem.

Regardless, I'm working on making idxstats work (albeit slowly) for cram and that same code will also make it work on sam and unindexed bam.

**Comment by swernig** [comment] 2018-04-26 10:50
it's a BAM file from Bowtie2 alignment, indexed with samtools for BAM files. I have also tried indexing with BAMtools. Even after redoing the alignment, converting SAM to BAM and indexing again, it doesn't work.

**Comment by sarawernig** [comment] 2018-04-26 15:42
The only difference I see is is that i used "samtools view -**S**b", but there is no reason this would make any difference. It's paired-end data if that changes anything? I'm using samtools v1.7.

**Comment by rotifergirl** [comment] 2024-04-23 03:53
Hi, I am having this same issue

Details: 
samtools v 1.20
pacbio reads (so not paired) mapped with minimap, sorted and indexed with samtools
flagstat output:
```
2962966 + 0 in total (QC-passed reads + QC-failed reads)
2535194 + 0 primary
357958 + 0 secondary
69814 + 0 supplementary
0 + 0 duplicates
0 + 0 primary duplicates
2962764 + 0 mapped (99.99% : N/A)
2534992 + 0 primary mapped (99.99% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```
idxstat finishes almost instantly and produces a contig name, length, and then the final two columns are just 0s all the way down

qualimap and hificnv can pull out the coverage data so I'm not sure what's going on here. I was trying to produce this file to feed to another analysis tool

**Comment by jkbonfield** [comment] 2024-05-13 13:29
Finishing almost instantly is expected as this data comes directly from the index.

Possibly the index is invalid?  If you delete the index or rename it away somewhere, and rebuild the index with "samtools index file.bam", does this still happen?  If so, what software produced your index?  Also which version of that software?  Is it a .bai or a .csi file?  What is the index filename (eg foo.bam.bai or foo.bai will also give us a clue as to whether it was produced by another tool).

**Comment by jkbonfield** [comment] 2024-05-13 14:27
Also, is your index a .bai or a .csi? (Or indeed do you have both present, which could explain some oddities maybe)

**Comment by jkbonfield** [comment] 2024-07-17 15:42
Closing this as it's been hanging around for years and no one has ever been able to reproduce it - not the developers, not apparently the people reporting the problem I assume given the lack of responses.

**Closed by jkbonfield** 2024-07-17 15:42 UTC
