### ISSUE TITLE
"make check" fails on 32-bit

### ISSUE THREAD

**Issue by jkbonfield** [samtools/samtools#379] opened 2015-04-14 13:18 UTC
I did a samtools build just now on my 32-bit deskpro and found that "make check" fails due to mpileup differences.

If you cd to the test/mpileup dir you can see the different results on 64-bit and 32-bit linux:

```
64-bit$ ../../samtools mpileup -x -F 0.60 -u -f mpileup.ref.fa indels.bam | ../vcf-m
iniview -f |awk '/INDEL/'
[mpileup] 2 samples in 1 input files
<mpileup> Set max per-file depth to 4000
17      547     .       A       AGCATCCTGCG     0       .       INDEL;I16=2,0,1,2,404,81608,538,130834,120,7200,180,10800,38,722,63,1347;QS=1.01515,0.984848        PL      111,0,51        22,0,54

32-bit$ ../../samtools mpileup -x -F 0.60 -u -f mpileup.ref.fa indels.bam | ../vcf-miniview -f |awk '/INDEL/'
[mpileup] 2 samples in 1 input files
<mpileup> Set max per-file depth to 4000
```

Basically it's failing to call the INDEL on 32-bit machines.  This isn't the only check to fail. There are several, but I am assuming related.  I don't see any memory issues with valgrind, so is this a loss of precision thing?

**Comment by jmarshall** [comment] 2015-04-14 13:32
Duplicate of #305.

**Closed by jmarshall** 2015-04-14 13:32 UTC
Labels: duplicate
