### ISSUE TITLE
[fai_build_core] different line length in sequence 

### ISSUE THREAD

**Issue by moldach** [samtools/samtools#1387] opened 2021-02-27 19:55 UTC
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

I'm running the latest version of `samtools` and `htslib`:

```
$ samtools --version
samtools 1.3.1
Using htslib 1.3.1
```

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)

```
$  uname -sr
Linux 4.18.0-193.28.1.el8_2.x86_64
$ gcc --version
gcc (GCC) 4.9.2
```

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

I'm trying to add a bacterial decoy sequence to a reference genome and index it using `faidx` (like described in [Samson _et al.,_ 2020](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwigh_Lew4rvAhVOsZ4KHXgKBHgQFjAAegQIBBAD&url=https%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC7648094%2F&usg=AOvVaw2Ivq_nJMyzAovoRSszcfyk) but running into an error with `samtools faidx` when attempting this with [reference genomes recommended by Heng Li](https://lh3.github.io/2017/11/13/which-human-reference-genome-to-use):

First [download the Synthetic bacterial decoy from Genbank (MT169739.1)](https://www.ncbi.nlm.nih.gov/nuccore/MT169739.1) and then the reference genome(s). Next concatenate them and then try to index with `samtools faidx`:

```
$ wget ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/reference/human_g1k_v37.fasta.gz
$ bgzip -d human_g1k_v37.fasta.gz
$ cat sequence.fasta >> human_g1k_v37.fasta
$ samtools faidx human_g1k_v37.fasta
[fai_build_core] different line length in sequence 'GL000192.1'.
Could not build fai index human_g1k_v37.fasta.fai

```

```
$ wget ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/reference/phase2_reference_assembly_sequence/hs37d5.fa.gz
$ bgzip -d hs37d5.fa.gz
$ cat sequence.fasta >> hs37d5.fa
$ samtools faidx hs37d5.fa
[fai_build_core] different line length in sequence 'hs37d5'.
Could not build fai index hs37d5.fa.fai
```

However, using `bwa-mem2 index` successfully creates the `.fai` for `human_g1k_v37.fasta` but **not** `hs37d5.fa`

**Comment by jmarshall** [comment] 2021-02-27 23:46
Your _sequence.fasta_ file does not have a `>` header line.

**Comment by moldach** [comment] 2021-02-28 22:37
Thanks for the quick response @jmarshall. Hmm that doesn't seem to be the problem;  the `sequence.fasta` does have a `>` header:
```
$ head sequence.fasta
>MT169739.1 Synthetic construct bacterial decoy, complete sequence
AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC
TTCTGAACTGGTTACCTGCCGTGAGTAAATTAAAATTTTATTGACTTAGGTCACTAAATACTTTAACCAA
TATAGGCATAGCGCACAGACAGATAAAAATTACAGAGTACACAACATCCATGAAACGCATTAGCACCACC
ATTACCACCACCATCACCATTACCACAGGTAACGGTGCGGGCTGACGCGTACAGGAAACACAGAAAAAAG
CCCGCACCTGACAGTGCGGGCTTTTTTTTTCGACCAAAGGTAACGAGGTAACAACCATGCGAGTGTTGAA
GTTCGGCGGTACATCAGTGGCAAATGCAGAACGTTTTCTGCGTGTTGCCGATATTCTGGAAAGCAATGCC
AGGCAGGGGCAGGTGGCCACCGTCCTCTCTGCCCCCGCCAAAATCACCAACCACCTGGTGGCGATGATTG
AAAAAACCATTAGCGGCCAGGATGCTTTACCCAATATCAGCGATGCCGAACGTATTTTTGCCGAACTTTT
GACGGGACTCGCCGCCGCCCAGCCGGGGTTCCCGCTGGCGCAATTGAAAACTTTCGTCGATCAGGAATTT

$ tail sequence.fasta
CCTGCTTTGATGCGTTCTTGACGATTCCGTCTTTGGTAATAACGATACCGCCGTATTCGTTAGCACTAGC
TGGCACGGGTCCTGCCTTGGGAATATCCTGCTTCTGCCCATTAATGAAGACAAAACCGACAATAATCACG
GCCACTAGGACAACCGCTAGCACACCCAGCTGCAGCAGGCGACGGTTTGATTTTGTTGGGTTATTGCGTG
CCTGTTTGGCCGCGATTTGACGGGCCTTTTCACGGGCATCGTTCGACATACCTGTTCCTTTTCTTGTAGG
ACGCACGACGCTGCGCCTTATCATTACCCCGTCTAGACTACCGAACTAGAGGATGCATATTCCAGCCATC
AGTCGATTTCTGCGGAGTTTCGGAGTTTTCTCACGCTCTCAGCTTATTTTACGACGCAAATATATGCCTT
TATGCAGATAGTGATGTCATGTTTCTCATACGGGGGTGAAGATACCAGGCGCCTTATAGCCCTGGCTTTT
TGTGTAGACCCCAAAACACCCACACCCCCTGTGGGGGCACAAAAAAGAGGGCCCCCACCAGGGGACCCCC
ACTCACAAAAAA
```

```
$ head human_g1k_v37.fasta
>1 dna:chromosome chromosome:GRCh37:1:1:249250621:1
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
$ tail human_g1k_v37.fasta
TTAGCGGGGCGTGGTGGCGCACACCTGTAATCCCAGCTACTCAGGAGGCTGAGGCAGGAG
AATCGCTTGAACCCGGAGGCAGAGGTTGCAGTGAGCCGAGATCATGCCATTGAACTCCAG
CCTGGGTAAAAAGAGCGAAACTCCGTCACAAAAAAACAAAACAACAACAACAACAAAAAC
ATATATATATATATATATATTACCAGACAGAAGATAGATAATCTGTGATTACTATGTCAA
GGACAATTTTAGAATACTTGTTAAATTCACCCCTTTCTTTTCACAGCTGGCCAGGACATA
GTCAGTAGCTACTGATACCTTGAATACCTTGGCTGTGTTAACTGTTTTGACCCATCATGG
AGCCAAGATGTTGGTTGTACCTTGAGATGCTGATCTGGCTGAAGTCCAGGGTCACGGGCC
CAGGATAGGTCATTCAGCTATTTGAAAAAAACAGAAGAGAGACCAGGCCATCCACTGAGG
TCATCTCCATGCAGCATGGGCCACTGGTTCCAGTGAACCCACCATCACCATACTTCTCAG
GAATCGCTGGTCACTAGACTGAGAGTTCTGTCAAAGCTGAGATCATAT
```

**Comment by jmarshall** [comment] 2021-02-28 22:57
Then, for the copy of _human_g1k_v37.fasta_ after you have concatenated _sequence.fasta_ on to it, please show us the output of

```
tail -n +51696827 human_g1k_v37.fasta | head
```

**Comment by moldach** [comment] 2021-03-01 03:00
Okay, first of all you are seeing a longer file than me.

```
tail -n +51696827 human_g1k_v37.fasta | head
```

Looks like bgzip might be failing to unzip the entire reference?

```
$ bgzip 

Version: 1.11
Usage:   bgzip [OPTIONS] [FILE] ...
Options:
   -b, --offset INT           decompress at virtual file pointer (0-based uncompressed offset)
   -c, --stdout               write on standard output, keep original files unchanged
   -d, --decompress           decompress
   -f, --force                overwrite files without asking
   -h, --help                 give this help
   -i, --index                compress and create BGZF index
   -I, --index-name FILE      name of BGZF index file [file.gz.gzi]
   -l, --compress-level INT   Compression level to use when compressing; 0 to 9, or -1 for default [-1]
   -r, --reindex              (re)index compressed file
   -g, --rebgzip              use an index file to bgzip a file
   -s, --size INT             decompress INT bytes (uncompressed size)
   -@, --threads INT          number of compression threads to use [1]
   -t, --test                 test integrity of compressed file
```

```
$  bgzip -d human_g1k_v37.fasta.gz
[E::inflate_gzip_block] Inflate operation failed: incorrect header check
[E::bgzf_read_block] Reading GZIP stream failed at offset 891985920
[E::bgzf_read] Read block operation failed with error 1 after 0 of 65536 bytes
Error 1 in block starting at offset 891985920(352AA000)
```

**Comment by jkbonfield** [comment] 2021-03-01 09:39
Not that it's related (probably) to your error, but:

>I'm running the latest version of samtools and htslib:
> 
> $ samtools --version
> samtools 1.3.1
> Using htslib 1.3.1

This is most definitely not the latest version.  It's some 5 years out of date.  You need to look hard at whatever packaging system claims this is the latest version as it's obviously wrong.

As for the problem, it's hard to reproduce as NCBI don't appear to have a useful website (no download link that I could find, just spewing 10s of Mb of HTML formatted fasta to my *local* web browser, not the server I'm sshed to.  Even the "Fasta (text)" is a piece of javascript to fetch and display the sequence, rather than a URI to the actual data I could just wget.  Not helpful!

However I suspect the problem is something like a missing trailing newline on the human genome or missing header on the other file, causing a malformed sequence entry.  I'd advise you to look carefully at the actual file post-concatenation to see what it's given you.  I expect there'll be an obvious error once checked.  Try something like:

```
grep -B3 AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC hs37d5.fa
```

That's the first line of the synthetic sequence you pasted on to the end of hs37d5.fa.  You *should* see the last couple lines of the original fasta (with newlines), the >MT169739.1 line and of course the sequence above.  As you say the file sizes differ, I expect a truncated initial file somewhere and the >MT line appearing half way through a sequence line, giving rise to the error.

**Comment by jmarshall** [comment] 2021-03-01 10:07
I suspect the problem with @moldach's downloaded file is more fundamental than that:

>     $  bgzip -d human_g1k_v37.fasta.gz
>     [E::inflate_gzip_block] Inflate operation failed: incorrect header check
>     [E::bgzf_read_block] Reading GZIP stream failed at offset 891985920
>     [E::bgzf_read] Read block operation failed with error 1 after 0 of 65536 bytes
>     Error 1 in block starting at offset 891985920(352AA000)

(BTW it's a plain gzipped file, which might more naturally be decompressed  with `gunzip`.)

**Comment by daviesrob** [comment] 2021-03-01 11:35
It's actually not a plain gzip file.  `gunzip` on it says:
```
gzip: hs37d5.fa.gz: decompression OK, trailing garbage ignored
```
and as noted the "trailing garbage" spooks `bgzip` which fails to decompress the complete file.  It turns out the clue is at the head of `hs37d5.fa.gz`:
```
$ hd hs37d5.fa.gz | head -n 2
00000000  1f 8b 08 04 00 00 00 00  00 03 07 00 52 41 5a 46  |............RAZF|
00000010  01 80 00 ec 9c cb 8e 64  c9 71 44 f7 f1 15 fc 04  |.......d.qD.....|
```

So it's actually a RAZF file, which was a [predecessor](https://lh3.github.io/2014/07/05/random-access-to-zlib-compressed-files) to BGZF (note that the linked page postdates the events described - RAZF appeared around 2008).  RAZF didn't last very long, so it's surprising to see a file using it in the wild.

`gzip` appears to give the right decompression, so that's probably the best way of dealing with this file.

**Comment by jmarshall** [comment] 2021-03-01 11:52
Well spotted, Rob. I saw that “trailing garbage” warning the first time I decompressed this, but didn't follow it up.

**Comment by moldach** [comment] 2021-03-01 18:45
Sorry @jkbonfield I forgot that `1.3.1` is _actually_ `1.03.1` and that this version preceedes `1.11`.
Thanks for looking more into this @jmarshall & @daviesrob - I'm going to book mark this in case I run into future problems with `bgzip`/`gunzip`.

Running `gzip -d human_g1k_v37.fasta.gz` returns: `decompression OK, trailing garbage ignored`.

After that, I was able to successfully index the references (even using the `1.3.1` version).

Thanks a bunch for getting to the bottom of this

**Comment by daviesrob** [comment] 2021-03-09 14:41
Future versions of bgzip should give a more helpful message when they come across one of these files.  Closing now, as it looks like they've been uncompressed successfully.

**Closed by daviesrob** 2021-03-09 14:41 UTC
