### ISSUE TITLE
samtools index [V1.2] fails when out.index parameter is set

### ISSUE THREAD

**Issue by magnusmanske** [samtools/samtools#447] opened 2015-08-05 09:08 UTC
> samtools index some.bam

generates some.bam.bai

> samtools index some.bam some.bam.bai

fails.

**Comment by jmarshall** [comment] 2015-08-05 09:12
Duplicate of #199; fixed in the upcoming release by 8f60492d1a81b362cf7630ee3ab8669fd21420e0.

**Closed by jmarshall** 2015-08-05 09:12 UTC
Labels: duplicate
