### ISSUE TITLE
Can't increase max per-file depth in mpileup

### ISSUE THREAD

**Issue by topherius** [samtools/samtools#645] opened 2017-02-27 19:26 UTC
Hi - 

I am piloting some deep sequencing on human blood samples using unique molecular identifiers (UMIs). This is new for me, but I have previously done plenty of calling and annotation on hybrid capture data using a pipeline based on samtools > varscan > annovar. I am trying to run these UMI-deduped BAMs through the same pipeline.

The UMI deduplicated depth for these files frequently exceeds 8000 reads per base (the default max set by mpileup), and in IGV I can see that in many cases the depth at a given position is often 14000-17000. However, I cannot get more than 8000 reads per base analyzed in the pipeline. 

I have tried adjusting per-file read depth (using -D 1000000000, for example), but this has had no effect. I have also tried combining this with -A and -Q0 to allow any orphans and low-quality reads, even though from my perusal of the BAMs I don't think this is the issue.

Is there something I am missing here that is preventing me from getting all reads per base? The pipeline was pretty old and was using an outdated version of samtools, but I tried upgrading to the latest version and that didn't fix the problem either.

Thanks - 

Chris

**Comment by jkbonfield** [comment] 2017-02-28 10:31
How are you determining that the depth is being ignored?  Is this mpileup VCF/BCF output and figures listed in there (in which case this is should be reported in bcftools) or the older textual pileup format?

For the current develop branch of samtools I can definitely see that altering the depth (-d not -D) does work, for both text pileup format and VCF.  I went to 40,000 depth just fine.  Can you supply us with a small demonstration, or perhaps the output you get and which field is incorrect?

Thanks.

**Comment by jkbonfield** [comment] 2017-03-07 15:31
Closing as unable to reproduce this issue in the samtools side of things and I suspect the problem lies with whatever tool you are using to analyse the VCF file instead.

If you have a demonstration of the issue and find that it is in the samtools part of the tool-chain then please reply and I'll reopen the issue (or make an issue in htslib if it's in that part).

**Closed by jkbonfield** 2017-03-07 15:31 UTC

**Comment by liufengxia99** [comment] 2017-08-10 07:22
I met the same question

Your environment

samtools 1.3.1 or 1.5

Steps to reproduce

/gpfs/software/pipeline/pipeline/tools/samtools mpileup -d 100000 -f /gpfs/software/pipeline/pipeline/database/ref/hg19/hg19.fasta -l /gpfs/software/pipeline/pipeline/region/region_59_188k/region_59_188_merged.bed /gpfs/project/59gene_188K/project_2samples_20170725.business/baidecheng_cf/qc/mapping/tumor/PM2017072404.final.bam > /gpfs/project/59gene_188K/project_2samples_20170725.business/baidecheng_cf/snv/pair/varscan/PM2017072404.pileup

Expected behaviour

positonal depth is about 2800X
samtools depth -r chr1:11856378-11856378 chr1_11856378.bam
chr1	11856378	2883

Actual behaviour

while mpileup output is only 1330X, and the reads between forward and reverse strand diff greatly
les tumor.chr1.PM2017072404.pileup.gz|grep -P "chr1\t11856378"
chr1	11856378	G	1330 .$.$,$......AAA.A...A.,a,,,AA.Aa,,aaa..A,AAAA.aa,,a.A,aaaa,,,,aaaa,,,,a,,.AAAAAa,,,a,.....AAaaaa,,aaa,a,,a,aaaAA.A.a..AAA.......A..AA,,aaa,,,,a,,,,,,aaaa,A.Aa,,....,.A.,,,..aa,.,a..,A,,A..Aa,,a,AA.A......aa....A.....AA.A.A..A..AAA.a,,a,aaA..AAA.a.AA.A.AA,,aAa,a,,AA..A....A..,....A..A....AAAAA.A...AA..A..A..AAAA,AAA..A...A...A.A..AAAA.A..AAA...AA...A,.AAAA...AA...AA..A..AAAA.A..AAA..AA,aA.AaAa,.....A.AAA.A......A.A..AAA..A...AAAA..A...AA.......AA......aa...A.,A...A..A.AA..AAA.A..A.A..A.AA..A....AA.AAA....AA.AA.,..A..A..A.......AAA...AA..A...A.AAAA...A..A..AA.A..AA.AAAAAAA..A....AA.A.AA...AA.A.A...A....A..A...AA...AA...A.AA.AA.....AA.A..AAAAA.A...AAAA............A..AAA..A.AA.AA.....AAA...AAA...A.AAAAA......A...A..A......A.AA.AAA.AA...AA..A....A...AA.AAA...AA...AA...A..AAA.AAA........aAAA..AA...AA....,aa,,AA..A.AA......AA.AA..AAAA..AA.Aa,,,,A.A..AA.A......AAAA.AAAAA.AA..A..A..A.AA.....AA.A....A.AA.....AA..AAA.AA.AA...A.A.......AA.AAA.AA....A...AA..AA.AA......AA.AA...AA.AAA..A...AA..........A...AA..AA.A...AA...a...A.A.....A.AA....A...A..A..AAAA....A.AAA.AAAAA...AAAAAA....A.....A.A.A,a,,aaAA...A..AA.AA..AAA...A......A...A....AA...AA....A.AAAA.A...A.A....A.AA.A...AA.A.A.AA.A.AA.A.A.aAAA.AAAA..AA.AA.....AA.A.A.......AAA.A..A..A..Aa..A.AA....A.A...A.A..AA.A.AA....AA..AA,AAA.AAAA..AAAA...A.AAAA..A.AAA..AA.A.A.A,AAA....^].^].	[QB]Y^__SSSYU_]]S]B0BBBT[_[?@@???bUTCbbbTeC3DDChgF5CDCAGFFCDDCGGG.CFFigf[ggDG4GDGjjjOlfgCDCDGGCDDFCFFDGDDCSSjgi@ljgddkfkljjjSjldgGFCCCGFGGDFFFGGFCCCDGgleDGFjjUjGlhjFAFjmDCGmGCgjFfGFekjSCGGDGgTmSkmllfmD=miiihkmimfheijegmfiQSgShCGG?GCDkhhhhkdhedjSUeSGFCSCFDGGdhmiTjillfmmBllkldKlSmlll;gggSlclilcemhhjlhmeddShGcggldTmKjcliigjgmfcagglflkeghmjjgTmmmgFjdgSgllkcglUlhcmjgmhTddemgjmhdSmmggFDSjTDggmmjlmmemhhcmdmlmhhmhmdlmfghmmfmmmddhhimhmmmhhmlglmhm@dlmmmmgCDmmmhmFhmlghlmfUhhkfTPhmfilhbgmhfmhhhmSimmmhhlegcmmmmdhhhhlGmmhmmhimhmmmmhmmTefmmmhammdmmmfmghfTmmmhmmdmmffhhmmhdmcgddffSmmTmmmmfSmhhhTmllgflSlgmm]clmlihmmfmmlSeimmdhimmhmhhmfhmiiQmdTVfmmgThddmhlmifchfmlglimmlllllglmggcildlffmcfmmmmmhhelmmhhhmcmhmhhfhhmmhmmmglmmhmmhmimmhmfmhhgfffghlelfflQflmQ:fllleemghcmmlcfmm]hfllmhfmhdhmfhhmlhhlmihhgfTlmghGllgemlfmfhgmlhfmlbmhhlmmlmjThmcTmmheccmlheldgmlmmhmhimfCmemmimmlhhhTmhhefhlhfllfimhmlhlhhjlmePgfmhmmmmhmhhmilmmcfmmfhglhghfgcllhifmlmmliahdmhheihgmfmmhmmehRjmhhmhejmllilghjhhmhmhhVhEflmgmmjfdlkkOhmmmmihmmiThjmggGcilhaclmhhmmmhmSiGmmmaBehmh^jelllZmlhLm^dRhmmmhUiggZmghdf^imhggegggjmGifllGmjgig_gmgmmhPgh\lmgjMhEmTgjmThhmmGhGmlhl\dimmfi^medhlmlghlKjldlfEhhmEmm\f_hghGGdldZlh_mlZflgGhGEgg_ggaE]TdhEEDmZEgLiFfhhTdGdheFfelEmIG\FFcGGECD\GGgEGlLlGBhFFDFIEGlG_MGgelBZjhG\CgmdFhgGGdG4fFGDDhcJEFDCCbGGEDOBF_FDFVeV9icCFELTjleDiENECKg<T:FfbfB[

**Comment by liufengxia99** [comment] 2017-08-10 07:36
while i return to samtools 0.1.19 , the depth up to 2400X, and the num of forward and reverse strands is much the same

**Comment by daviesrob** [comment] 2017-08-10 13:40
@liufengxia99  Would it be possible to get hold of your input files, or alternatively a public data set that shows the same behaviour?  It's difficult to look into this without having something that reproduces the problem.
