### ISSUE TITLE
samtools rmdup error (version 1.2) "Samtools-htslib-API: bam_get_library() not yet implemented"

### ISSUE THREAD

**Issue by yuifu** [samtools/samtools#491] opened 2015-11-24 02:38 UTC
samtools rmdup brings out error even though it is version 1.2.

`Samtools-htslib-API: bam_get_library() not yet implemented`

**Comment by jmarshall** [comment] 2015-11-24 08:45
Duplicate of #159 et al.  This has been fixed (13de48f8dd6bcd71277128143fadc9ab3aa50576, PR #461), and an `rmdup` command that works as well as it ever did will reappear in the upcoming 1.3 release.

**Closed by jmarshall** 2015-11-24 08:45 UTC
