### ISSUE TITLE
1.10 segfaults on pysam tests but 1.9 doesn't

### ISSUE THREAD

**Issue by rollf** [samtools/samtools#1183] opened 2020-02-02 21:22 UTC
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)

```
samtools 1.10
Using htslib 1.10
Copyright (C) 2019 Genome Research Ltd.

vs

samtools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.
```

 #### Please describe your environment.
```

$ uname -sr
Linux 5.3.0-18-generic
$ gcc --version
gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
Copyright (C) 2019 Free Software Foundation, Inc.
```

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

```
$ git clone https://github.com/pysam-developers/pysam.git --depth 1
Cloning into 'pysam'...
remote: Enumerating objects: 805, done.
remote: Counting objects: 100% (805/805), done.
remote: Compressing objects: 100% (725/725), done.
remote: Total 805 (delta 111), reused 356 (delta 52), pack-reused 0
Receiving objects: 100% (805/805), 4.37 MiB | 717.00 KiB/s, done.
Resolving deltas: 100% (111/111), done.
$ cd pysam/tests/pysam_data/
$ samtools --version
samtools 1.10
Using htslib 1.10
Copyright (C) 2019 Genome Research Ltd.
$ make ex1.bam # with samtools 1.10
samtools faidx ex1.fa
samtools import ex1.fa.fai ex1.sam.gz ex1.bam
make: *** [Makefile:56: ex1.bam] Segmentation fault (core dumped)
make: *** Deleting file 'ex1.bam'
```
Updating $PATH to use samtools 1.9 yields:

```
$ cd pysam/tests/pysam_data/
$ samtools --version
samtools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.
$ make ex1.bam
samtools faidx ex1.fa
samtools import ex1.fa.fai ex1.sam.gz ex1.bam
```

The 1.10 version of samtools segaults whereas the previous version does not.

**Comment by mr-c** [comment] 2020-02-03 08:53
Here is one of the patches Debian used to fix this: https://salsa.debian.org/med-team/python-pysam/blob/master/debian/patches/hts1.10#L4

**Comment by jkbonfield** [comment] 2020-02-03 09:29
Wow - `samtools import` is a command I'd never heard of before!

Apparently it was removed in 2009: 521aa49c29217a0398ff5e186072df97cf9d80c4

It's not part of our test harness and it isn't supported.  I had no idea we apparently still actually honoured the code for this (it's been absent from the help / usage message since 2009).  I think our best line of fix here is just to nuke main_import entirely as it's clearly not being maintained and tested.

**Comment by jmarshall** [comment] 2020-02-03 09:39
It's a trivial wrapper for an early format conversion command (that pysam, for their sins, is still using), and the fix for this (prepend `argv[-1]` to `argv2`) is trivial… 🤷‍♂

**Comment by jkbonfield** [comment] 2020-02-03 09:41
Yes, I can see the cause - it didn't have an argv[-1], that bit is trivial.

However this command was removed (from help at least) in 0.1.5!  I'd rather not be carrying around dead code that almost no one knew existed.  While we could trivially bug fix it, but preference is complete removal.

**Comment by jmarshall** [comment] 2020-02-03 12:52
And yet it appears in an astonishing number of tutorials and web pages out there — search for ["samtools import"](https://www.google.com/search?q=%22samtools+import%22). So it's worth considering whether removing the command will lead to an educational opportunity for the readers of those web pages or will lead to them filing issues here about its disappearance…

**Comment by jkbonfield** [comment] 2020-02-03 13:49
Maybe, although most of those google hits are old conversations with people replying with "it's deprecated".

There are more modern things if you look, but I don't really see the point given it was removed from documentation a decade ago.  (If only a warning message had been added at the time, but water under the bridge.)

The fact is it's taken over a month for anyone to notice it doesn't work, and that was purely an automated test rather than a user.  It clearly can't be THAT popular.

**Closed** 2020-02-05 11:14 UTC

**Comment by rollf** [comment] 2020-02-06 08:00
Okay, thanks for the quick replay. I was also surprised this hasn't been reported before given that it was used in pysam's automatic tests.
