### ISSUE TITLE
-M option not working with indexed cram files 

### ISSUE THREAD

**Issue by jjfarrell** [samtools/samtools#972] opened 2018-10-30 18:38 UTC
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
Yes, 1.9
 #### Please describe your environment.
Linux 2.6.32-696.28.1.el6.x86_64

#### Please specify the steps taken to generate the issue, the command you are running

samtools view -h   -T /restricted/projectnb/casa/ref/GRCh38_full_analysis_set_plus_decoy_hla.fa -M hg38_ver5.bed  /restricted/projectnb/adsp/wgs.hg38/adsp.cc/cram/A-CUHS-CU006299-BL-COL-49783BL1.hg38.realign.bqsr.cram|tail
[main_samview] random alignment retrieval only works for indexed BAM or CRAM files.
@SQ     SN:HLA-DRB1*14:05:01    LN:13933
@SQ     SN:HLA-DRB1*14:54:01    LN:13936
@SQ     SN:HLA-DRB1*15:01:01:01 LN:11080
@SQ     SN:HLA-DRB1*15:01:01:02 LN:11571
@SQ     SN:HLA-DRB1*15:01:01:03 LN:11056
@SQ     SN:HLA-DRB1*15:01:01:04 LN:11056
@SQ     SN:HLA-DRB1*15:02:01    LN:10313
@SQ     SN:HLA-DRB1*15:03:01:01 LN:11567
@SQ     SN:HLA-DRB1*15:03:01:02 LN:11569
@SQ     SN:HLA-DRB1*16:02:01    LN:11005

But the cram file is indexed with a crai file.

**Comment by jmarshall** [comment] 2018-10-30 22:04
Several things have conspired to make this a fantastically misleading error message. Once PR samtools/htslib#721 has landed, the error message will instead be

```
samtools view: failed to open "hg38_ver5.bed" for reading: Exec format error
```

which is a clue that the problem is that the BED file is being interpreted as the SAM/BAM/CRAM file to be viewed.

So in fact you need `… -M -L hg38_ver5.bed …` — this is as documented but is perhaps not the clearest user interface ever.

**Comment by valeriuo** [comment] 2018-11-07 10:31
We've added a [note](https://github.com/samtools/samtools/commit/e415187e61c395a33333066bb3d38a3520d49a9c) in the man page, instructing users to put **-L** before the BED file. We cannot print an error message, at this point, because the BED file is optional. The target regions could be specified as command line arguments only. If nothing is provided, you do get an error message in the form:

`[main_samview] no regions or BED file have been provided. Aborting.`

**Closed by valeriuo** 2018-11-07 10:31 UTC
