### ISSUE TITLE
`fqidx` should preserve input FASTQ line wrapping by default

### ISSUE THREAD

**Issue by jmarshall** [samtools/samtools#1734] opened 2022-10-14 13:04 UTC
As [reported on Twitter by Keith Robison](https://twitter.com/OmicsOmicsBlog/status/1578468479585644545), `samtools fqidx` by default uses the same line wrapping as `faidx`:

```
$ cat eighty.fq 
@one
ATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGC
+
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
$ samtools fqidx eighty.fq 
$ samtools fqidx eighty.fq one
@one
ATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGC
ATGCATGCATGCATGCATGC
+
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
qqqqqqqqqqqqqqqqqqqq
$ samtools fqidx -n9999 eighty.fq one
@one
ATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGC
+
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
```

While some “FASTQ specifications” probably suggest the format allows seq and qual to be line wrapped, most implementations expect a FASTQ record to be exactly four lines. So they would choke on the default `fqidx` output.

So I would suggest that the default `line_len` value for `fqidx` should be INT_MAX. This would change the default output formatting (for reads longer than 60 bases), but IMHO this is not really a compatibility issue as the minority of FASTQ consumers that can actually accept the existing line-wrapped FASTQ output should be equally happy with 4-line FASTQ.

**Comment by jkbonfield** [comment] 2022-10-18 14:41
There are essentially two different uses of FASTQ out there now.

The original use was for old Sanger-style technology input data or for consensus sequences from assemblies.  Line wrapping was normal.  No one really cares about indexing the former, but the latter is very obviously worthy of indexing and that is the purpose of fqdix (and obviously faidx).  Think of a fasta reference file, but with a base confidence attached per nucleotide.  One humungous line for the seq and quality is unwieldy.

Then there is the NGS data which started with a few hundred bases of 454 and 25bp Solexa data, which has subsequently grown to long-read NGS.  These started the trend of 4 line fastq entries.  Using fqidx on such data would be an abomination!  It's totally not what it was intended for, so this isn't the sort of data we need to be considering when judging output styles.

Instead we need to think of the consumers of this data.  What is likely to be reading a portion of a reference file, specified with quality values in fastq instead of fasta?  Traditionally it's going to be alignment tools.  Most of the common modern ones I can think of (eg bwa, fastq) don't support fastq references, but some of the older traditional tools do (eg smalt) as well as minimap2.
Those examples do support very long fastq lines, but I wouldn't necessarily assume it's a given, nor that they are the same efficiency (EMBOSS seqret was 45% slower on 4-line data than line-wrapped stuff, presumably due to the need to repeatedly realloc the `fgets` input buffer until it found one large enough to work).

What's the justification for requiring long lines here instead of wrapping?  Ie what tool is it that is taking **consensus** / **reference** and requiring it to look like the *read* format?  I'm wondering if changing the default is just going to lead to complaints in the other direction about why some legacy tool used to be able to read our fastq and no longer can.

This is perhaps best dealt with in documentation.

**Comment by jkbonfield** [comment] 2022-10-19 14:13
I think I'd be in favour of `-n 0` just being a synonym for no wrapping, but we could add an explicit `--single-line` option too as it's trivial.

Either way (keep or change default) it's probably a storm in a tea cup as the option exists to control this so it just boils down to either fixing downstream tools or using the appropriate option to give them data they can swallow, plus I'd expect the number of times people abuse(?) the tool in this way is very low.

[ Personally I'm (ab)using it right now for something subtly different - output from `samtools consensus` where I do actually care about the confidence value assigned to the consensus base, so I can skip places of dubious provenance.  It's far nicer to generate a consensus once and twiddle a dial for that than it is to have to recreate it over and over again with different base -> "N" thresholds.  Although where my particular abuse comes in is ambiguity codes to indicate heterozygous indels. :) ]

**Comment by jmarshall** [comment] 2022-10-19 15:01
I think trying to fix downstream tools would be an endless task — the 4-line records for FASTQ reads thing is pretty entrenched, and is useful when writing hacky scripts.

The important point is about this tool having two distinct domains of usage, with wrapping being appropriate for one but not the other. The default is set up for the reference consensus original domain, which means handling the other one (sequencing reads data, admittedly a bit of a dubious usage!) is then a matter for documentation and a succinct option — I like that `-n 0` idea.

(Reads-based users might not _read_ the documentation, but at least it'll be there to point at!)

**Comment by jkbonfield** [comment] 2022-10-19 15:40
To be clear, I'm only *assuming* the original intent for fqidx given the name and extreme similarity to faidx, along with its use on references instead of individual read sequences.  Plus what I personally are using it for, which post-dates fqidx.  Maybe @mp15 can clarify the origins as it was #805 where this originated.   I cannot really remember the reasoning at the time.

Anyway,  I'll look at clarifying the documentation and updating the CLI.

**Comment by krobison13** [comment] 2022-10-19 22:24
A significant use case is that there are Linux one-liners based on AWK or Perl circulating on Twitter (an undoubtedly other places)  that rely on the common pattern of FASTQ  records being 4 lines

[grep FASTQ records with a pattern](https://twitter.com/tangming2005/status/1572584725822201857?s=20&t=dJ_ns_U0jMy94O-y9x3jQg)

[split FASTQ into multiple files with set number of reads per file](https://twitter.com/lucacozzuto/status/1565275956310425604?s=20&t=dJ_ns_U0jMy94O-y9x3jQg)

[subsample a FASTQ](https://twitter.com/tangming2005/status/1564251075993128960?s=20&t=dJ_ns_U0jMy94O-y9x3jQg)

[extract 5' barcodes](https://twitter.com/tangming2005/status/1569686633733029890?s=20&t=dJ_ns_U0jMy94O-y9x3jQg)

[compute read length distribution - from 2018!](https://twitter.com/Psy_Fer_/status/1067902276784742401?s=20&t=dJ_ns_U0jMy94O-y9x3jQg)


[And who would want to stand in the way of this concept?: "awk one-liner to convert FASTQ to Nature paper"](https://twitter.com/arminscheben/status/1283204040667652096?s=20&t=dJ_ns_U0jMy94O-y9x3jQg)

Seriously, the ability to use AWK/Perl at command line to run simple, useful analyses will be easier if this change is made

**Comment by jmarshall** [comment] 2022-10-19 22:55
I totally agree that the 4-line simplification is particularly useful when writing hacky scripts operating on reads data.

James suggests that `fqidx`'s intended data type is FASTQ reference assemblies, akin to the usual FASTA reference file but with base qualities attached. Thus **not** reads data. So each chromosome might be several megabases or more, and both the input reference file and the output from `fqidx` would be line-wrapped — just as is expected with `faidx`.

Indeed, the `fqidx` documentation contains a note pointing out that there's not much point using it with Illumina-style sequencing reads FASTQ data: if you have millions of short reads, not much indexing is going to occur.

So I guess the real question is: What does your source data look like (is it reads? how long? is the original source FASTQ line-wrapped or 4-line records?), and what are you doing to it conceptually when you query parts of it with `samtools fqidx`?

**Comment by krobison13** [comment] 2022-10-20 02:25
It is a bit of an edge case, but it does make fqidx a bit of an outlier in the bioinformatics space

For PacBio and Oxford Nanopore reads or synthetic reads such as from LoopSeq,  it isn't uncommon for me to want to have random access retrieval, particularly when pulling out sequences for debugging a tool (e.g. the sequences that are tripping things up) 

PacBio tends to move things around as unaligned BAM, but for compatibility with other tools it is common to convert this to FASTQ .  ONT  outputs 4 line FASTQ records in my experience.

I suppose my one other plea would be consistency -- samtools fastq outputs 4 line records. Of course, that's opening up a new can of worms as samtools fasta outputs 2 line records!  So the tools are consistent within a given command, but inconsistent for a given sequence file type -- and I'm asking you to switch that to consistent within a sequence file type but inconsistent within a command!

**Comment by jmarshall** [comment] 2022-10-20 05:16
`samtools fastq` deals solely with reads data. As discussed, `fqidx` likely has a dual nature (dealing with two file types represented in the same format) and by default is consistent with `faidx`.

However there is a way for `fqidx` to be consistent with both world views: preserve the formatting from the input file:

* The default output line width should be the same as the line width in the indexed input file, i.e., it should be LINEBASES (column 4) from the fai/fqi index for the queried chromosome.

This would be an improved default for the `faidx` command too, though the maintainers may be reluctant to change that after all these years.

**Comment by jkbonfield** [comment] 2022-10-20 08:21
> I suppose my one other plea would be consistency -- samtools fastq outputs 4 line records. Of course, that's opening up a new can of worms as samtools fasta outputs 2 line records! So the tools are consistent within a given command, but inconsistent for a given sequence file type -- and I'm asking you to switch that to consistent within a sequence file type but inconsistent within a command!

This is precisely the correct analogy.  samtools faidx / fqidx are a pair that manipulate raw read data, and samtools fasta / fastq are also a pair that manipulate assembly consensus and reference sequences.

You're confusing the *type* of data with the data *format*.  Raw reads and references / assemblies are completely different types of data, and are consumed by a different type of tool.   So for consistency, are you also suggesting here that samtools fasta shouldn't line wrap references by default too?   As for this needing to be done because it makes it easy to process in awk, perl, etc.  No one is saying fqidx should not be able to output the 4 line format.  It already can.  Anyone writing a one-liner should at least think about the appropriate command line parameters to use.

However John's proposal seems reasonable about querying the input format and repeating the same wrapping level as it shouldn't break anything.

**Comment by jmarshall** [comment] 2022-10-20 09:19
👍 but I think you have them the wrong way around in the first paragraph 😄

**Comment by jkbonfield** [comment] 2022-10-20 10:32
Oops yes :).   Anyway, we discussed it as a team and thought your proposal to be the right approach, so thanks.

**Comment by krobison13** [comment] 2022-10-20 13:39
"You're confusing the type of data with the data format. Raw reads and references / assemblies are completely different types of data, and are consumed by a different type of tool. "

Ouch.  I'd argue I am most certainly **_not_** confused about anything and instead represent a growing segment of the samtools community. 

Ultralong nanopore reads from genomes are now routinely longer than a BAC or most viruses and we see increasing numbers longer than the smallest bacterial chromosomes or even yeast chromosomes.

HiFi PacBio or LoopSeq reads are often both raw data and effectively references when the interest is in single molecule libraries such as for protein engineering or synthetic biology. 

So I fail to see a useful ongoing distinction between raw data and references/assemblies and would argue that the community at large finds such a distinction confusing.  I find that samtools faidx/fqidx are routinely useful in these contexts for working with my datasets and it would be more convenient & consistent with most tools if 4-line FASTQ records were output.

**Comment by jkbonfield** [comment] 2022-10-20 14:52
Well the PR now exists, so it's a moot point. :-)

However I do obviously understand that long read technologies exist.  I also understand that they can, in some specific scenarios, be taken to be a finished product and fed into all the usual tools we have for handling consensus sequences and assemblies, such as alignment tools (Martin's example of using EMBOSS needle on twitter falls exactly into that category).

Note my statement wasn't that the data is different, but the *purpose* was different.  That I feel still holds true.  Data we are using as a finished product (whether or not it's a genuine assembly or a single read fulfilling that role) is typically processed by tools that already handle line-wrapped data.  (See "needle" example above.)   Perhaps some more modern software doesn't properly honour the full FASTQ specification,  but if so IMO that's simply sloppy coding.

> So I fail to see a useful ongoing distinction between raw data and references/assemblies and would argue that the community at large finds such a distinction confusing. I find that samtools faidx/fqidx are routinely useful in these contexts for working with my datasets and it would be more convenient & consistent with most tools if 4-line FASTQ records were output.

Let's be clear, it always could output 4-line FASTQ.  We're not talking about a new feature here, but about saving a few characters of extra typing (the "-n" option).

I didn't initially feel like changing from line-wrapped to non-wrapped format was a good idea as I know there will probably *also* exist tools that process line-wrapped formats and may have a liimt on the individual length of any individual line.  So I was wary of solving one problem while making another.  However John's suggestion was a sensible one, hence the PR.

**Closed** 2022-10-20 16:40 UTC
