### ISSUE TITLE
samtools stats coverage output bug (when using bowtie)

### ISSUE THREAD

**Issue by jodyphelan** [samtools/samtools#1029] opened 2019-03-20 23:16 UTC
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.

samtools 1.9
Using htslib 1.9

 #### Please describe your environment.
- OS: Linux 4.15.0-36-generic
- machine architecture: x86_64
- compiler: gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

`samtools stats` outputs too many sites on the COV output when analysing BAM files produced by bowtie2 when looking a a specific region (the sum of the number of sites is more than the size of the region). This behaviour is not seen with BAMs produced with bwa.

To replicate this issue see [this gist](https://gist.github.com/jodyphelan/c26862404bc05c4e3129d22d8f4bb4e4).

**Comment by valeriuo** [comment] 2019-03-21 09:57
Thanks for the report! 
I have a guess it might be related to #1025, for which there is an open pull request #1027. I will check your data, anyway.

**Comment by valeriuo** [comment] 2019-03-21 10:25
Yes, it's the same issue. You can pull the PR branch, if you need the fix now.
Duplicate of #1025

**Comment by valeriuo** [comment] 2019-03-21 10:32
Duplicate of #1025

**Comment by jodyphelan** [comment] 2019-03-21 10:43
Great thanks!

**Comment by valeriuo** [comment] 2019-03-25 16:06
Fix in develop

**Closed by valeriuo** 2019-03-25 16:06 UTC
