### ISSUE TITLE
Error when piping in BAM data to samtools on Windows

### ISSUE THREAD

**Issue by divonlan** [samtools/samtools#2061] opened 2024-05-27 20:18 UTC
Any BAM file piped into samtools on Windows results in the same error:

$ cat file.bam  | samtools.exe view
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
[E::bgzf_read_block] Invalid BGZF header at offset 0
[E::bgzf_read] Read block operation failed with error 2 after 0 of 4 bytes
[E::bam_hdr_read] Invalid BAM binary header
[main_samview] fail to read the header from "-".
samtools view: error closing "-": -1

This doesn't occur on Linux, it doesn't occur for sam, sam.gz or cram files, and also doesn't occur when removing the BGZF compression:
zcat file.bam  | samtools.exe view

And interestingly also doesn't when redirecting the input like this:
samtools.exe view < file.bam

Smells like a somehow misconfigured pipe allowing Windows to mess it up with a BOM and/or LF->CRLF conversions.

Tested on samtools 1.17 running on mingw-64, installed via pacman.

**Comment by jkbonfield** [comment] 2024-06-03 10:15
I don't see this.

```
$ cat test/mpileup/mpileup.1.bam | ./samtools.exe view|wc
    569   11914  248727
```

This was develop, but I don't think we've changed that much.  I'll test htslib & samtools 1.17

```
$ ./samtools.exe --version
samtools 1.20-15-g4685e1e
Using htslib 1.20-21-g5d318680-dirty
Copyright (C) 2024 Genome Research Ltd.

Samtools compilation details:
    Features:       build=configure curses=yes
    CC:             gcc
    CPPFLAGS:       -D_XOPEN_SOURCE=600
    CFLAGS:         -Wall -g -O2
    LDFLAGS:
    HTSDIR:         ../htslib
    LIBS:           -lregex
    CURSES_LIB:     -lncursesw

HTSlib compilation details:
    Features:       build=configure libcurl=yes S3=yes GCS=yes libdeflate=yes lzma=yes bzip2=yes plugins
=no htscodecs=1.3.0
    CC:             gcc
    CPPFLAGS:       -D_XOPEN_SOURCE=600
    CFLAGS:         -Wall -g -O2 -fvisibility=hidden
    LDFLAGS:        -fvisibility=hidden

HTSlib URL scheme handlers present:
    built-in:    preload, data, file
    S3 Multipart Upload:         s3w, s3w+https, s3w+http
    Amazon S3:   s3+https, s3+http, s3
    Google Cloud Storage:        gs+http, gs+https, gs
    libcurl:     imaps, pop3, gophers, http, smb, gopher, sftp, ftps, imap, smtp, smtps, rtsp, scp, ftp,
 telnet, mqtt, ldap, https, ldaps, smbs, tftp, pop3s, dict
    crypt4gh-needed:     crypt4gh
    mem:         mem
```

**Comment by jkbonfield** [comment] 2024-06-03 10:48
Works for me under a fresh 1.17 build from the release tarball.

Maybe this is dependent on your environment.    My mingw gcc is mingw-w64-x86_64-gcc 12.2.0-5.  I've tried doing an update which appeared to download and reinstall the same versions again.  Shrug.

As expected, it still works for me.

Maybe it's something specific to your BAM file.  Does the test/mpileup/mpileup.1.bam work for you?

**Comment by jkbonfield** [comment] 2024-06-03 11:10
As to the cause for you.

It could be the [EOF check](https://github.com/samtools/htslib/blob/develop/bgzf.c#L1538-L1557) failing, but that would be easy to test by adding a `return 2;` statement to the top of the function.  I'm wondering if it's something to do with errno not being reset before calling hseek, but that's just a guess.  However for me even if I return 0, -1 or 2 from there it still works, albeit with warnings.

So the alternative is as you suggest - an ASCII vs binary problem.    Binary mode is set in https://github.com/samtools/htslib/blob/develop/hfile.c#L740-L742:

```
#if defined HAVE_SETMODE && defined O_BINARY
    if (setmode(fd, O_BINARY) < 0) return NULL;
#endif
```

However even with that commented out, it still works due to this code in samtools [bamtk main](https://github.com/samtools/samtools/blob/develop/bamtk.c#L227-L230) function.  I can get `cat file.bam | test_view -` to fail however with the hfile.c code commented out as test_view doesn't have its own `O_BINARY` safe guard.

However I don't get exactly the same errors you see:

```
cat ../test/mpileup/mpileup.1.bam | ./test/test_view.exe - | grep ERR013140.6157908               [E::bgzf_read_block] Failed to read BGZF block data at offset 0 expected 5148 bytes; hread returned
299
[E::bgzf_read] Read block operation failed with error 4 after 0 of 4 bytes
[E::bam_hdr_read] Invalid BAM binary header
Couldn't read header for "-"
Error closing input.
```

However CR-LF issues would be very much data specific so they could show up in a variety of places with different errors.  If this is the cause, it implies `HAVE_SETMODE` failed for you.  It's defined in hfile.c itself:

```
#ifndef _WIN32
#include <sys/socket.h>
#include <sys/stat.h>
#define HAVE_STRUCT_STAT_ST_BLKSIZE
#else
#include <winsock2.h>
#define HAVE_CLOSESOCKET
#define HAVE_SETMODE
#endif
```

You could try changing the `if defined` so it always passes, to see if it's the autodetection that isn't working for you for some reason.  I can't see how not though.

Are you building with ./configure, or just make?  Are you using htslib and samtools as the same version, or mixing different releases.  If so, which ones?

**Comment by jkbonfield** [comment] 2024-06-27 10:59
In experimenting with GitHub Actions recently, which came with it's own MSYS2 gcc, I reminded myself that installing the mingw-w64 version of gcc is not enough.  It puts it into a subdirectory, but your PATH still points to the msys2 gcc instead.  That doesn't define `_WIN32` and instead has `__CYGWIN__` defined.  I did try changing the ifdefs but it then blew up with the O_BINARY macro, but I haven't investigated further to see if cygwin has its own alternatives there.

Regardless, I don't feel the need to spend a lot of time supporting multiple version of windows compilers given our official support is for Mingw-w64.

Can you try adding /mingw64/bin to the start of your PATH?

**Comment by jkbonfield** [comment] 2024-06-27 11:23
Correct.  However if you're using the lower level POSIX `open()` call then the `O_BINARY` flag does not, sadly, exist outside of Windows.  So there's no analogue for this there.

If you're definitely picking up the mingw-w64 gcc then I cannot explain this problem.  For me, it works just fine.  You'll need to do some debugging yourself probably by putting in `#warning` to various bits of code to see which code paths the compiler is taking in the ifdef checks.  It feels like it's simply not defining `_WIN32`, but I could be wrong.

**Comment by jkbonfield** [comment] 2024-06-27 11:51
I meant debugging in htslib.c not the compiler.  Like I say, I installed using pacman and it still wasn't the first gcc in my path!

**Comment by jkbonfield** [comment] 2024-07-18 12:06
Closing this as dormant and unable to reproduce.  My belief is still that this is likely a misconfiguration.  Both locally and remotely in AppVeyor and GitHub CI it works provided PATH is set correctly.

**Closed by jkbonfield** 2024-07-18 12:06 UTC
