### ISSUE TITLE
[Question]: Guidance with using multiple threads with samtools view/sort/index

### ISSUE THREAD

**Issue by tamuanand** [samtools/samtools#1931] opened 2023-10-23 00:20 UTC
Hi

I have question on number of threads to use with samtools sort/view/index.  Does the tool scale linearly with more cpus/more threads and have corresponding decrease in time? Does using the `--fast` option with `samtools view`  along with increased number of threads help in speed up of processing of large WGS bam files

I am using EC2 r6i.8xlarge - 32cpus, 256 GB 

Thanks in advance.

**Comment by jkbonfield** [comment] 2023-10-24 08:07
The `--fast` option is basically `gzip -1` style compression, and naturally this makes it faster to compress.  Decompression is not affected, but compression is usually the bottleneck.

How well the number of threads scales depends on the subcommand.  On some it is very poor with maybe 2 threads worth being the maximum as the main CPU is in the main thread with only I/O (de)compression being the threaded part.  In others, such sort there are significant portions that can be multi-threaded, but it won't be totally linear.   My advice is simply to try a few experiments and see, as it may be data specific as well as command specific.

I will also suggest that where possible you use pipelines to pipe one command into another, and when doing so use uncompressed BAM as the intermediate format between pipes.  The use of `mbuffer` between commands can *sometimes* help a little also to remove pipe buffer blockages, but it depends a lot on the workload.  Also note you can avoid a lot of pointless file format conversion, which is sadly still common place in many online tutorials.  All the sub-commands take all the SAM,BAM,CRAM formats, so there is no need to convert SAM to BAM before sorting for example.

**Comment by jkbonfield** [comment] 2023-10-24 08:32
Closing now as the question was answer and it's also a duplicate of https://www.biostars.org/p/9578282/ (which has a comparable anwer too).

**Closed by jkbonfield** 2023-10-24 08:32 UTC
