### ISSUE TITLE
Container header CRC32 failure

### ISSUE THREAD

**Issue by ernfrid** [samtools/samtools#693] opened 2017-06-19 14:19 UTC
I have at least one CRAM file that reports this error during indexing. The CRAM was created using samtools1.3.1 linked to htslib1.3.2

The indexing job itself succeeds and the index file size looks normal. I don't understand the implications of the error message. I am observing, possibly related, errors in downstream tools. 

I have a few question:

What does this error indicate with respect to the contents of the CRAM? Is this error indicating a fundamental corruption of the file? Or should it be recoverable and the downstream tools need better error handling?

Are there any recommendations for troubleshooting or fixing this issue?

Thanks!

**Comment by jkbonfield** [comment] 2017-06-19 14:36
The error message means that the contents of the CRAM container header does not match the computed checksum (see pic 5 from https://github.com/samtools/hts-specs/blob/master/CRAMv3.pdf for the general structure of a CRAM file).

This sounds like a data corruption, possibly through file-system errors, a random memory bit-flip or (more likely tbh) a coding error.  Indexing a CRAM skips through the file decoding container and slice headers, but not the data within the slices themselves.  In this regard I would expect a normal ```samtools view``` to produce the same error, albeit slower, but it's worth validating it that way too incase the error is something related to the indexing code and not where I think it is.

Do you still have the original data or some way of reproducing the steps that created it?  I can't see any changes to the CRC calculations since 1.3.1 so it would be good to know if this is a repeatable issue.

**Comment by ernfrid** [comment] 2017-06-19 15:09
Thanks for replying so quickly James!

I will attempt a samtools view and see if I see the error. I expect that I will as at least one of the downstream tools I was using also reported it.

This is a file from a collaborator and I am querying them to see what is still available and hopefully we can determine if it's repeatable.

**Comment by ernfrid** [comment] 2017-06-19 18:56
Running samtools view on the file results in the following messages:

```
Container header CRC32 failure
[main_samview] truncated file.
```

**Comment by jkbonfield** [comment] 2017-06-20 08:03
Ok that's pretty much as expected.  It sounds like this was considered a failure by samtools view, which is correct.  I deem it to be a bug if  ```samtools index``` succeeded (assuming it did return a zero exit code) after emitting that error message.  Notwithstanding the original cause of the corruption also.

**Comment by ernfrid** [comment] 2017-06-20 13:49
It does seem to be returning 0 in the version I've been testing:
```
$ samtools --version
samtools 1.3.1
Using htslib 1.3.2
Copyright (C) 2016 Genome Research Ltd.
$ samtools index bad.cram
Container header CRC32 failure
$ echo $?
0
```

**Comment by valeriuo** [comment] 2017-07-03 16:47
Hi, Dave!
Have you managed to reproduce the issue, starting from the original file?
Best!

**Comment by ernfrid** [comment] 2017-07-05 13:35
I don't have any new information yet, but we're hoping to have more by the end of the week.

**Comment by ernfrid** [comment] 2017-07-10 19:15
Looks like this issue wasn't reproducible.

**Comment by jkbonfield** [comment] 2017-07-11 08:06
That's good to hear.  I'll close this then under the assumption it was a data corruption during file transfer or local disk storage rather than a bug in the software.

**Closed by jkbonfield** 2017-07-11 08:06 UTC

**Comment by ernfrid** [comment] 2017-07-11 11:03
Sounds good. @jkbonfield - Should I open a separate issue for the samtools index bug you mentioned or is that already taken care of?
