### ISSUE TITLE
samtools depth not use the "bam_mplp_init_overlaps" 

### ISSUE THREAD

**Issue by TuBieJun** [samtools/samtools#966] opened 2018-10-22 03:24 UTC
I found the depth stat of "samtools depth" and "samtools mpileup" are different in the same position. Then I found that "bam2depth" not use the "bam_mplp_init_overlaps" func, when I add this, the results of two command is same.So cound you add this feature in the next release, becase an overlap pair reads shoud be counted once.

**Comment by tseemann** [comment] 2018-10-23 04:29
Duplicate of https://github.com/samtools/samtools/issues/967 due to github issues on 2018-10-22 ?

**Closed** 2020-06-28 02:05 UTC
