### ISSUE TITLE
Completely autotool the buildsystem

### ISSUE THREAD

**Issue by SoapGentoo** [samtools/samtools#558] opened 2016-04-09 22:23 UTC
Dear samtools maintainers,
I am inquiring to ask whether you would be willing to entertain the idea of completely autotooling the buildsystem. There are multiple reasons for preferring Automake over hand-written Makefiles:

- Proper flag ordering, which is important for distributions that use "-Wl,--as-needed" for instance
- Maintenance is much easier, as mundane targets (such as clean) are autogenerated
- Standard directories and flags are respected (`DESTDIR` and friends)
- Parallel building is much simplified

If you are willing to accept such a proposal, I would be willing to send in a PR (for the htslib and bcftools ofc too).

Regards
David

**Comment by jmarshall** [comment] 2016-04-10 10:11
Duplicate of #277, samtools/htslib#137, and samtools/bcftools#240.

We are familiar with automake and do not wish to use it.

**Closed by jmarshall** 2016-04-10 10:11 UTC
