### ISSUE TITLE
Performance issues with high coverage regions in markdup

### ISSUE THREAD

**Issue by Poshi** [samtools/samtools#1771] opened 2022-12-14 10:39 UTC
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
Using the latest version available:
```
$ samtools version
samtools 1.16.1
Using htslib 1.16
```

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
```
$ uname -sr
Linux 3.10.0-1160.76.1.el7.x86_64
```
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
```
$ uname -m
x86_64
```
- compiler (run `gcc --version` or `clang --version`)
```
$ gcc --version
gcc (GCC) 12.1.0
```

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.
I'm just trying to run markdup on a bam file, with not many fancy flags:
`samtools markdup -d 2500 -@ 16 in.bam out.bam
`
The command probably works fine and gives good results. But not in a timely manner. It looks like that the time goes really up when it hits regions with a few thousands reads of coverage.
I've been doing some benchmarks and it runs at around 50Kreads/s in my test system, but in regions with high coverage it slows down to 0.3Kreads/s. This happens when most of the positions in the region have between 1000 and 10000 reads starting there.
I suspect that the optical duplicate marking involves a quadratic computation (didn't checked the code), so not sure how much optimization margin there exist. But I know that the processing of the entire bam file did not finish in 14 days. And I'm not even sure if it finished the first chromosome.
It would be nice to have some optimizations there, or at least, an option to set the biggest group to disambiguate, so in case of hitting big duplicate groups, only check for optical duplicates if the size is below the threshold. Not sure how to set the DT tag informing that the duplicate is neither a PCR nor an optical one.

**Comment by whitwham** [comment] 2022-12-14 11:51
Yes, duplicate marking and especially optical duplicate marking, does begin to suffer at high depth.

Assuming I cannot have your data to play around with, you could try:
`samtools markdup -d 2500 -@ 16 --no-multi-dup in.bam out.bam`
All duplicates will still be marked but some of the optical ones will be missed when there are a lot of duplicates in the same place.

It would be interesting to see what the time difference is if you don't look for optical duplicates at all.

> It would be nice to have some optimizations there

It might be related to  #1325, that was fixed but not perfectly.

>  an option to set the biggest group to disambiguate, so in case of hitting big duplicate groups, only check for optical duplicates if the size is below the threshold

There was such an option in a test version but it never made it to production code.

> Not sure how to set the DT tag informing that the duplicate is neither a PCR nor an optical one.

The dt tag only really has those two states.  What other kind(s) of duplicates are you looking for?

**Comment by Poshi** [comment] 2022-12-14 15:37
Well, I didn't got the numbers without looking for optical duplicates, but I checked how the `--no-multi-dup` option affects, and the differences can be quite relevant:
```
$ export TIMEFORMAT="%3R"
$ samtools view -b -o test.1-85064000-85064500.bam "${in_bam}" -e 'rname == "1" && pos >= 85064000 && pos <= 85064500' 1:85064000-85064500
$ { echo "time" 1>&2; for i in {1..10}; do time samtools markdup -d 2500 --no-multi-dup -@ 16 test.1-85064000-85064500.bam out.bam; done; } 2> timings.no-multi-dup.csv
$ { echo "time" 1>&2; for i in {1..10}; do time samtools markdup -d 2500 -@ 16 test.1-85064000-85064500.bam out.bam; done; } 2> timings.multi-dup.csv
$ mlr --icsv --opprint --from timings.multi-dup.csv stats1 -a count,min,mean,max,stddev -f time
time_count time_min time_mean          time_max time_stddev
10         103.192  130.35229999999999 144.781  12.71360792440768
$ mlr --icsv --opprint --from timings.no-multi-dup.csv stats1 -a count,min,mean,max,stddev -f time
time_count time_min time_mean time_max time_stddev
10         3.067    3.4997    4.161    0.3125134841535289
```
It can be seen that we went down from 103s to 3s, a little bit more than 37x.

In any case, that option is kind of obscure. Its description does not make crystal clear neither what is doing nor which are the performance implications. The description says that "stops checking for correctness". On one side, I would expect the calculus to be correct by definition (correctness of the definition should be checked in the unit tests after compiling). On the other side, I would expect some warning in case some value is incorrect (never saw any). In any case I would NOT expect an output change. And being a check, I would expect its performance penalty to be small compared to the real calculus. Maybe a good rewording of this option could help understand what it is doing and which are the risks of using it.

I'm not looking for other types of duplicates, but if you set a threshold for how big a duplicate group can be for optical/PCR classification, all the reads that are over the threshold cannot be reliably marked as any of them. They should be marked as "undecided" or "undetermined" or "unknown".

Regarding the dataset, it's a very small excerpt from the whole dataset, so with proper anonymization I could send it to you. Do you want me to send you the file? Privately, as the data should not be made public.

**Comment by Poshi** [comment] 2022-12-14 16:14
Just sent you a mail with the test data. I hope I didn't get the wrong address.

**Comment by whitwham** [comment] 2022-12-15 17:52
> In any case, that option is kind of obscure

Yes, yes it is.  I put it there just in case someone, somewhere needed to use it.  I had no real expectations of it being used.

> Its description does not make crystal clear neither what is doing nor which are the performance implications.

No, I didn't make much of an effort with describing it, though it does mention a speed increase.  Again, I wasn't really expecting it to be used.

> The description says that "stops checking for correctness".

Maybe "completeness" would be a better word than "correctness".  The expensive piece of code this option bypasses is marking duplicates of optical duplicates as optical duplicates (even if they don't normally qualify).  It's expensive because the duplicates can appear in any order and they need to be checked against each other (in a particular range in the contig) which limits some of the easier solutions.  Whether this kind of duplicate marking is a good or helpful idea is up for debate, but it is what we were asked to do.

>  On the other side, I would expect some warning in case some value is incorrect (never saw any).

That is because there is no real definition of "correct" when it comes to duplicate marking.  There is no standard we can check ourselves against.  What we try to be is consistent.

>  In any case I would NOT expect an output change. 

You should expect an output change.  Most of markdup's options will change the result depending on which options you use.  They should, however, be the same result with the same data each time (with the same version of the software).

> And being a check, I would expect its performance penalty to be small compared to the real calculus.

The "real calculus" of finding a duplicate is only done once per read and is therefore very fast.  Seeing if a read is an optical duplicate adds another check and a bit more work but it is not too bad.  Checking to see if a duplicate of a duplicate should be marked as an optical duplicate is a pain because it involves keeping lists of duplicates till just before they are written out and checking them against each other while trying to avoid O(n^2) complexity.

 > Maybe a good rewording of this option could help understand what it is doing and which are the risks of using it.

Yes, though I think the entire markdup man page needs fleshing out.  It is all a bit sparse.  I have an item on my to-do list to write up how duplicate marking works in samtools and why.  Maybe 2023 is the year I will be able to write it and then I can update the man page on the basis of that document.

Thank you for your data, it will be very helpful.  I will look at it when I get back to work in the New Year.

**Comment by Poshi** [comment] 2022-12-15 22:24
> > The description says that "stops checking for correctness".
> 
> Maybe "completeness" would be a better word than "correctness". The expensive piece of code this option bypasses is marking duplicates of optical duplicates as optical duplicates (even if they don't normally qualify). It's expensive because the duplicates can appear in any order and they need to be checked against each other (in a particular range in the contig) which limits some of the easier solutions. Whether this kind of duplicate marking is a good or helpful idea is up for debate, but it is what we were asked to do.

And "searching" would be a better word than "checking" too. Or any other word that implies change, and not only check.

> That is because there is no real definition of "correct" when it comes to duplicate marking. There is no standard we can check ourselves against. What we try to be is consistent.

I fully agree with that: there's no clear definition of what an optical duplicate is. It is kind of obvious when you get the common explanation, but when you have to go down to the details and edge cases, it is no clear at all. Like, what happens if a position have two PCR duplicates (far away from each other) and each one have a bunch of optical duplicates? Do we get a primary, a PCR dup and all the others are optical? Or maybe one is marked as primary, the closest ones are optical and the others are considered PCR? The results can be really different with different definitions of "optical duplicate".
Having which is the definition implemented in the code would be a very good point. Right now, if someone wants to know have to read the code or prepare a test set to see when a read is marked and how.

> You should expect an output change. Most of markdup's options will change the result depending on which options you use. They should, however, be the same result with the same data each time (with the same version of the software).

But the documentation said that that option stopped checking for correctness (whatever definition of "correct" you decided to use), so I assumed it was a **check**, not something that could modify results. And if results are going to be modified, the users need to know how this can affect the results to take an informed decision weather to use it or not.

> > And being a check, I would expect its performance penalty to be small compared to the real calculus.
> 
> The "real calculus" of finding a duplicate is only done once per read and is therefore very fast. Seeing if a read is an optical duplicate adds another check and a bit more work but it is not too bad. Checking to see if a duplicate of a duplicate should be marked as an optical duplicate is a pain because it involves keeping lists of duplicates till just before they are written out and checking them against each other while trying to avoid O(n^2) complexity.

I was assuming that the O(n^2) calculus was always done, so the bigger the duplicate group, the exponentially bigger time penalty for the calculus. That's why I was asking for a parameter to limit this size and leave the duplicate type undecided for big groups.

BTW, for reference, the time needed to process the full file from where the excerpt I sent you came was around 17 hours (including preprocessing, aligning, duplicate marking and statistics, everything serial) using Picard MarkDuplicates, but when using the samtools markdup (and a parallelized pipeline, so it should be faster), it went over 14 days and did not finished, stuck at markdup :-(

**Comment by whitwham** [comment] 2023-01-12 13:28
> The results can be really different with different definitions of "optical duplicate".
Having which is the definition implemented in the code would be a very good point. Right now, if someone wants to know have to read the code or prepare a test set to see when a read is marked and how.

Agreed. It really is time I got around to writing out how samtools markdup works and what assumptions it makes.

> but when using the samtools markdup (and a parallelized pipeline, so it should be faster), it went over 14 days and did not finished, stuck at markdup :-(

The last time we had this kind of problem I managed to reduce the running time for markdup from 7+ days to 40 minutes (that was with 800k duplicates per original).  Your data has a different pattern but, for the test data you provided, I have o lowered the time from 4 minutes to 12 seconds.

The code should be ready for a PR in a day or so.  If you could test your full data on the new version that would be helpful.

**Comment by Poshi** [comment] 2023-01-12 13:51
I just sent you a random sample that happen to take much time, but the original file is way bigger and more prominent patterns can be there.
I re-tried that file with a time limit of 30 days and it didn't finished either. It would be a pleasure to try new code with the same data and see if it goes down to a single digit number of hours.

**Closed** 2023-01-19 11:16 UTC

**Comment by Poshi** [comment] 2023-01-19 13:55
On a first, quick try, on the file I provided you, I went from 125.26s (7.43 stddev) in v1.16.1 to 4.70s (0.24 stddev) in commit eb703e0 (current HEAD).
Assuming that the results are the same/equivalent, this is a huge speedup! Almost 27x. I'll try the full version of the input, which is a 200GiB BAM file, approx. With this speedup, the more than 30 days it was taking can be reduced to less than 2. Let's see.

**Comment by Poshi** [comment] 2023-01-19 15:37
Defnitely it's a lot faster for this kind of dataset. The full dataset (200GiB uncompressed BAM/31GiB compressed BAM) took 26m1.006s and generated a 31GiB output, while the old version started 1h ago and only managed to generate 245MiB output so far.
