### ISSUE TITLE
bam -> cram Problems with fasta header

### ISSUE THREAD

**Issue by jd3234** [samtools/samtools#1627] opened 2022-03-29 10:49 UTC
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
```bash
samtools --version
samtools 1.15
htslib 1.15
```

 #### Please describe your environment.
- OS 
```bash
uname -sr
Linux 4.15.0-161-generic
```
- machine architecture
```bash
uname -m
x86_64
```
- compiler
```bash
gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
```

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

- bwa mapping
- samtools sort
- picard dedup

And the problematic step
```bash
samtools view -@ 1 -C -T reference.fasta -o out.cram in.bam
bgzf_read() on reference file: No such file or directory
[main_samview] failed to write the SAM header
```
This worked before for other samples with other references. So looking at this reference file.

```bash
grep ">" reference.fasta
>chr1 description description_2
>chr2 description description_2
```
The fasta header has two spaces and the descriptions are identical except the second description has a bit more information. All references used before had only one description -> one space. Could this be the problem?

None of the upstream used tools had a problem with the header and other samtools commands also do not seem to mind it... So maybe it is just a problem for the bam -> cram conversion?

Fixing the fasta file to have only one description solved the problem.

**Comment by jkbonfield** [comment] 2022-03-31 14:48
I cannot reproduce this locally.  I started with

```
./samtools view -o /tmp/_.cram -T test/dat/view.001.fa test/dat/view.001.sam
```

After lots of variation of test/dat/view.001.fa I cannot reproduce this error.  So I suspect there is something more subtle than simply the format of the description fields.  Are you rerunning `samtools faidx` after changing it in your tests.  (I assume so or it's likely to break in more disastrous ways.)

Is there anything else weird about your reference, such as blank entries, or extra long lines?

I'll have a manual read through the code incase I spot anything obvious, but it'd be easier if I could reproduce the bug.

Thanks.

**Comment by jkbonfield** [comment] 2022-03-31 15:02
A dive through the code shows this is likely not a code problem.

FAIDX format is:

```
chr1    248956422       112     80      81
chr2    242193529       252068602       80      81
chr3    198295559       497289663       80      81
chr4    190214555       698064029       80      81
chr5    181538259       890656400       80      81
...
```

That's chr, chr len, seq offset, base length, line length (eg +1 for newline).  Offset 112 here is because the file starts:

```
>chr1  AC:CM000663.2  gi:568336023  LN:248956422  rl:Chromosome  M5:6aef897c3d6ff0c78aff06ac189178dd  AS:GRCh38
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
...
```

112 is the first "N".


Our fasta reading code uses:

```
    offset = e->line_length
        ? e->offset + (start-1)/e->bases_per_line * e->line_length +
          (start-1) % e->bases_per_line
        : start-1;

    len = (e->line_length
           ? e->offset + (end-1)/e->bases_per_line * e->line_length +
             (end-1) % e->bases_per_line
           : end-1) - offset + 1;
```

e->offset, e->line_length come and e->bases_per_line come from the
FAIDX file.

So we turn position in chr (1 based) to 0 based, divide by number of bases per line to get the Nth line, multiply by line_length and add to FAIDX offset field to get the file position, and then do a modulo to get the position within that line. This permits us to do a direct file seek.

Len is basically the same thing for the end coordinate instead, and then substracted from offset (start).

Then if the computed "len" is less than the end-start+1 then we know we have some line-wrapping to resolve, so it removes anything outside the '!' to '~' range (ie printable 7-bit ASCII).

This all seems quite logical, but most importantly of all, it all happens *after* the ">name comment" FASTA header.

I cannot see how changing this could affect anything.  It is more likely that your .fa file was replaced with a newer version containing the comments, but you didn't redo a "samtools faidx" to correct it.  A subsequent manual edit then brought the fai file back into agreement with the old version.

Could this be the cause for your error?

**Comment by jd3234** [comment] 2022-04-06 07:21
Hi James,
thanks for looking into that problem. First I wanted to say that it is not possible that the faidx build did not fit because the sequences are highly integrated in our systems and if a file changes a new faidx index should be build automatically. But no system is perfect so we will dig into this and check if we have a bug on our side.
I will let you know. Thanks again!

**Comment by jkbonfield** [comment] 2022-04-06 08:07
I guess if you ever observe this issue again in the future, move the fai file out of the way and rebuild it so you can compare.

**Comment by jkbonfield** [comment] 2022-04-19 12:58
Closing due to lack of recent feedback and evidence of a bug.  Please reply if you subsequently manage to verify this wasn't an outdated .fai file.

**Closed by jkbonfield** 2022-04-19 12:58 UTC
