### ISSUE TITLE
Failure to decode slice in "CRAM to bam"

### ISSUE THREAD

**Issue by jianguozhouzunyimedicaluniversity** [samtools/samtools#1640] opened 2022-04-25 07:11 UTC
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.
(run `samtools --version`)
````
(samtools1) [zhou@localhost bam]$ samtools --version
samtools 1.15.1
Using htslib 1.15.1
Copyright (C) 2022 Genome Research Ltd.

Samtools compilation details:
    Features:       build=configure curses=yes 
    CC:             /opt/conda/conda-bld/samtools_1649352267887/_build_env/bin/x86_64-conda-linux-gnu-cc
    CPPFLAGS:       -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/zhou/miniconda2/envs/samtools1/include
    CFLAGS:         -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/zhou/miniconda2/envs/samtools1/include -fdebug-prefix-map=/opt/conda/conda-bld/samtools_1649352267887/work=/usr/local/src/conda/samtools-1.15.1 -fdebug-prefix-map=/home/zhou/miniconda2/envs/samtools1=/usr/local/src/conda-prefix
    LDFLAGS:        -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/home/zhou/miniconda2/envs/samtools1/lib -Wl,-rpath-link,/home/zhou/miniconda2/envs/samtools1/lib -L/home/zhou/miniconda2/envs/samtools1/lib
    HTSDIR:         
    LIBS:           
    CURSES_LIB:     -ltinfow -lncursesw

HTSlib compilation details:
    Features:       build=configure plugins=yes, plugin-path=/home/zhou/miniconda2/envs/samtools1/libexec/htslib libcurl=yes S3=yes GCS=yes libdeflate=yes lzma=yes bzip2=yes htscodecs=1.2.2
    CC:             /opt/conda/conda-bld/htslib_1649384579568/_build_env/bin/x86_64-conda-linux-gnu-cc
    CPPFLAGS:       -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/zhou/miniconda2/envs/samtools1/include
    CFLAGS:         -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/zhou/miniconda2/envs/samtools1/include -fdebug-prefix-map=/opt/conda/conda-bld/htslib_1649384579568/work=/usr/local/src/conda/htslib-1.15.1 -fdebug-prefix-map=/home/zhou/miniconda2/envs/samtools1=/usr/local/src/conda-prefix -fvisibility=hidden
    LDFLAGS:        -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/home/zhou/miniconda2/envs/samtools1/lib -Wl,-rpath-link,/home/zhou/miniconda2/envs/samtools1/lib -L/home/zhou/miniconda2/envs/samtools1/lib -fvisibility=hidden -rdynamic

HTSlib URL scheme handlers present:
    built-in:    preload, data, file
    S3 Multipart Upload:         s3w, s3w+https, s3w+http
    Amazon S3:   s3+https, s3+http, s3
    libcurl:     imaps, pop3, gophers, http, smb, gopher, sftp, ftps, imap, smtp, smtps, rtsp, scp, ftp, telnet, mqtt, https, smbs, tftp, pop3s, dict
    Google Cloud Storage:        gs+http, gs+https, gs
    crypt4gh-needed:     crypt4gh
    mem:         mem
````

 #### Please describe your environment.
- OS (run `uname -sr` on Linux/Mac OS or ` wmic os get Caption, Version` on Windows)
- machine architecture (run `uname -m` on Linux/Mac OS or ` wmic os get OSArchitecture` on Windows)
- compiler (run `gcc --version` or `clang --version`)
````
(samtools1) [zhou@localhost bam]$ uname -sr
Linux 3.10.0-1160.53.1.el7.x86_64
````

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

 Failure to decode slice, but my download was succeed.
````
fa=~/t12b/reference/hg38_ek12/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa
(samtools1) [zhou@localhost bam]$ 
(samtools1) [zhou@localhost bam]$ samtools view -b  -T ${fa} -o ${dir}/bam/${i}.bam ${dir}/cram/${i}/*.cram
[E::cram_decode_slice] MD5 checksum reference mismatch at #0:121097333-143904328
[E::cram_decode_slice] CRAM: 3bda1f974fb8e843f11d62ead4b07c63
[E::cram_decode_slice] Ref : f6f06cbd5c205656a5e8de9f7abc42fa
[E::cram_next_slice] Failure to decode slice
samtools view: error reading file "/home/zhou/raid/ncbi/dbGaP-24835/RNA_phs001623/cram/SRR13977555/020_posttreatment_tumor_rna_H_VB_Merck004_m4_d14_RNA.cram": No such file or directory
(samtools1) [zhou@localhost bam]$ 
````
Best,
JG

**Comment by jianguozhouzunyimedicaluniversity** [comment] 2022-04-25 07:14
[information.xlsx](https://github.com/samtools/samtools/files/8552388/information.xlsx)
Information for SRR1397755.

**Comment by jkbonfield** [comment] 2022-04-25 08:45
Unfortunately this sample isn't public, so I cannot test it.

Are you certain it downloaded correctly?  Does the upstream archive have an md5 or sha256 (or similar) checksum for the file so you can validate it?

Also does the SAM header (`samtools view -T in.cram`) give hints on the MD5 for the first choromosome?  I'm assuming the first ref (`#0`) is chr1.  You can validate this manually.  Eg (for GRCh37, but the process would be the same with "chr1" instead of "1" for GRCh38):

```
$ samtools view -H ~/scratch/data/9827_2#49.1m.bam|egrep 'SN:1[^0-9]'
@SQ	SN:1	LN:249250621	UR:ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/phase2_reference_assembly_sequence/hs37d5.fa.gz	AS:NCBI37	M5:1b22b98cdeb4a9304cb5d48026a85128	SP:Human

$ samtools faidx $HREF 1|egrep -v '^>' | tr -dc a-zA-Z|md5sum
1b22b98cdeb4a9304cb5d48026a85128  -
```

We see those checksums match.  That's the entire chromosome.

The CRAM error message above though is a slice checksum.  To speed up validating of decoding while doing random access, each slice of data also has the checksum for that region alone.  We can see this specific region (using GRCh38 now):

```
samtools faidx $HREF38 chr1:121097333-143904328|egrep -v '^>' | tr -dc a-zA-Z|md5sum
f6f06cbd5c205656a5e8de9f7abc42fa  -
```

That matches the "[E::cram_decode_slice] Ref : f6f06cbd5c205656a5e8de9f7abc42fa" line in the error message above.  However for some reason the CRAM file has recorded a different checksum for that portion of data, implying the reference used perhaps wasn't identical to your local one (nor mine).  I'm hoping this isn't a software bug but is something that can be explained by the data provenance fields in the CRAM file - specifically the SQ lines.  I checked the reference and there are no other characters in the canonical reference than ACGTN, so there's nothing unexpected going on there.

**Comment by jianguozhouzunyimedicaluniversity** [comment] 2022-04-25 09:40
Dear @jkbonfield, thanks for your reply.
I checked the md5.
````
(samtools1) [zhou@localhost bam]$ md5sum ${dir}/cram/${i}/*.cram

3acce3e728aa5d32531f6dc60eb73e7c  /home/zhou/raid/ncbi/dbGaP-24835/RNA_phs001623/cram/SRR13977555/020_posttreatment_tumor_rna_H_VB_Merck004_m4_d14_RNA.cram
````
Right now, I already requested the md5 documents for all samples. I will update to you ASAP.
Best,
JG

**Comment by jkbonfield** [comment] 2022-04-27 09:10
Doing further checking on data here, trying to deliberately break things, I can reproduce this issue.

The cause would indeed appear to be specifying the wrong reference.  I am working on a PR to improve the error messages to make this a bit more obvious.  An example (local version):

```
$ samtools view -T /tmp/_.fa ~/scratch/data/novaseq.10m.cram 1:30000-33000 > /dev/null
[E::cram_decode_slice] MD5 checksum reference mismatch at 1:9996-33571
[E::cram_decode_slice] CRAM  : 028a858776b968fda1dc816b3f2f9047
[E::cram_decode_slice] Ref   : 53e2e287394963611d72fbee43900a8d
[E::cram_decode_slice] @SQ M5: 1b22b98cdeb4a9304cb5d48026a85128
[E::cram_next_slice] Failure to decode slice
samtools view: retrieval of region 0 failed due to truncated file or corrupt BAM index file

$ samtools view -T $HREF ~/scratch/data/novaseq.10m.cram 1:30000-33000 > /dev/null
```

Here `$HREF` is the correct copy of my reference (GRCh37 here) and `/tmp/_.fa` is a local copy where I edited the sequence for chr 1 to introduce a difference.

CRAM has fetched the relevant portion from my local reference, checksummed it, and validated that it matches the reference used for encoding that slice in the CRAM file.  They differ, hence the error message.  This strongly hints that you are giving the CRAM file the wrong reference.  Now included in the error above is the relevant portion of the header SQ line:

```
[E::cram_decode_slice] @SQ M5: 1b22b98cdeb4a9304cb5d48026a85128
```

Our preference would be to not specify the reference at all and let it use the M5 tag to fetch and cache the appropriate reference itself using GA4GH refget API.  However we acknowledge this isn't always possible and sometimes you wish to specify it locally.  

So can you please do the following?

1.  Report the whole header SQ line for chr1:
    `samtools view -H in.cram|egrep 'SN:(chr)?1[^a-z0-9_]'`

2. Compute the md5sum for chr1 in your local reference:
    `samtools faidx $fa  chr1|egrep -v '^>'|tr -d '\012'|md5sum`

**Comment by jianguozhouzunyimedicaluniversity** [comment] 2022-04-27 11:26
Thank for your reply.


````
i=SRR13977555
dir=~/raid/ncbi/dbGaP-24835/RNA_phs001623
cd ${dir}
mkdir -p bam
cd ${dir}/bam
fa=~/t12b/reference/hg38_ek12/Homo_sapiens.GRCh38.dna_sm.primary_assembly.f
samtools view -T ${fa} ${dir}/cram/${i}/*.cram 1:30000-33000 > nohup.txt
````
please check the file:
[nohup.txt](https://github.com/samtools/samtools/files/8571549/nohup.txt)


````
(samtools1) [zhou@localhost bam]$ samtools view -H ${dir}/cram/${i}/*.cram|egrep 'SN:(chr)?1[^a-z0-9_]'
@SQ     SN:1    LN:248956422    UR:/gscmnt/gc2552/uppaluri/zlsReheaderCrams/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa       AS:GRCh38-ensembl-primary       M5:8bffd97bbd14d38b00301bf24ce91d66     SP:human
````

The other is error.

````
(samtools1) [zhou@localhost bam]$ samtools faidx ${fa} chr1|egrep -v '^>'|tr -d '\012'|md5sum
[W::fai_get_val] Reference chr1 not found in FASTA file, returning empty sequence
[faidx] Failed to fetch sequence in chr1
````
Thanks!
JG

**Comment by jkbonfield** [comment] 2022-04-27 11:39
Something fishy here then.  GRCh37 used chromosome names 1, 2, 3, etc while GRCh38 switched to chr1, chr2, chr3.  Your CRAM file and local reference appear to be using the GRCh37 nomenclature but claim to be GRCh38 derived.

Anyway, the second command can be fixed with `samtools faidx ${fa} 1|egrep -v '^>'|tr -d '\012'|md5sum` instead.

Does it return the same as the CRAM SQ header (8bffd97bbd14d38b00301bf24ce91d66)?  My guess would be no.

**Comment by jianguozhouzunyimedicaluniversity** [comment] 2022-04-27 11:42
hi @jkbonfield it's worked.

````
(samtools1) [zhou@localhost bam]$ samtools faidx ${fa} 1|egrep -v '^>'|tr -d '\012'|md5sum

5b116cf6db50b1b659481505c70acf51  -

````

**Comment by jianguozhouzunyimedicaluniversity** [comment] 2022-04-27 11:47
but the md5 of cram is not match this md5.
````
(samtools1) [zhou@localhost bam]$ md5sum ${dir}/cram/${i}/*.cram
3acce3e728aa5d32531f6dc60eb73e7c  /home/zhou/raid/ncbi/dbGaP-24835/RNA_phs001623/cram/SRR13977555/020_posttreatment_tumor_rna_H_VB_Merck004_m4_d14_RNA.cram
````

**Comment by jkbonfield** [comment] 2022-04-27 11:50
Ok so that differs.  Actually I forgot one thing, which may not matter anyway.  The checksum used in CRAM and related protocols such as refget is uppercase only, so ideally that would be:

```
samtools faidx ${fa} 1|egrep -v '^>'|tr a-z A-Z | tr -d '\012'|md5sum 
```

It probably doesn't matter though as most people only ever use uppercase in their references.

Anyway, what this is telling you is that the reference differs to the one used to encode CRAM.

I tried to fetch the reference for this SQ line using the EBI refget server and it fails:

```
wget https://www.ebi.ac.uk/ena/cram/md5/8bffd97bbd14d38b00301bf24ce91d66
--2022-04-27 12:48:26--  https://www.ebi.ac.uk/ena/cram/md5/8bffd97bbd14d38b00301bf24ce91d66
...

So whoever produced this CRAM file used a local non-standard reference and didn't lodge it with the EBI.  You will need to ask whoever you got the CRAM file from for a copy of their reference too if you wish to decode it.
2022-04-27 12:48:26 ERROR 404: Not Found.
```

**Comment by jianguozhouzunyimedicaluniversity** [comment] 2022-04-27 11:53
Hey @jkbonfield Thanks for your update.
I will share this issue with the PI of phs001623.
Best,
JG

**Comment by jkbonfield** [comment] 2022-04-27 11:57
We should probably take it up with the EBI and NCBI too.  They shouldn't be storing CRAM files in their archives without having the appropriate references in their refget servers, as otherwise they're basically unusable.  I thought the EBI already did this check, but possibly it's only for data that is submitted to them directly and not for data they mirror from NCBI.  (The SRR name here implies it came via the SRA route.)

**Comment by jmarshall** [comment] 2022-04-27 11:58
> Something fishy here then. GRCh37 used chromosome names 1, 2, 3, etc while GRCh38 switched to chr1, chr2, chr3.

_Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa_ is the filename of a reference genome downloadable from Ensembl, and Ensembl still use `1`, `2`,`3`, etc without a `chr` prefix.
(Which remains IMHO the [1TCNS](https://en.wikipedia.org/wiki/Indentation_style#Variant:_1TBS_(OTBS)) :smile:)

Assuming this is indeed the file the OP is using, it would be good to recalculate the MD5s with the `tr a-z A-Z` bit: the _dna_sm_ in the filename indicates that this edition of the assembly has had repeats and low complexity regions soft-masked to lowercase.

**Comment by jianguozhouzunyimedicaluniversity** [comment] 2022-04-27 11:59
````
 samtools faidx ${fa} 1|egrep -v '^>'|tr a-z A-Z | tr -d '\012'|md5sum 
2648ae1bacce4ec4b6cf337dcae37816  -
````

**Comment by jianguozhouzunyimedicaluniversity** [comment] 2022-04-27 12:00
> We should probably take it up with the EBI and NCBI too. They shouldn't be storing CRAM files in their archives without having the appropriate references in their refget servers, as otherwise they're basically unusable. I thought the EBI already did this check, but possibly it's only for data that is submitted to them directly and not for data they mirror from NCBI. (The SRR name here implies it came via the SRA route.)

This dataset from dbGap

**Comment by jkbonfield** [comment] 2022-04-28 08:18
So definitely there is a reference mismatch:  SQ line has "M5:8bffd97bbd14d38b00301bf24ce91d66" while your md5sum calculation was different.  The software therefore is working correctly, and the recent PRs improved the error messages to make the cause of failure more obvious.

It does raise bigger questions with input validation at dbGap though, although that's not our problem.  They need to check the reference sequences are public, or at least host a copy of the reference along with the files (they can be deduplicated trivially so it shouldn't be vast).  EBI already have a validation in place to ensure all CRAMs use references in their refget server, so they don't have the same flaws that NCBI do.  However apparently EGA doesn't mirror dbGap.  (I wrongly assumed it would given ENA mirrors SRA and dbGAP is using SRR* naming conventions.)

@jmarshall I'd already downloaded the ensembl version of this reference and it gave a different md5sum.  It's possible there are many versions of the reference, or possibly there's some other weird characters in there too.  It's all a bit cack really.  In theory CRAM makes data provenance a bit easier with the mandating of M5 tag, but as we see here it's simply making it easy to tell we're bad at data provenance, which is one step better than not knowing but hardly solving the problem. :-)  Also if Ensembl are making edited versions of the reference, they really ought to consider lodging them with the refget server that their own institution runs!  Speak to your colleagues... sigh

(FWIW I've started looking again at improving support for embedded references, as with deep data at least the extra overheads really aren't that bad given it's essentially a fixed 750MB addition per file regardless of file size, and considerably less for WES or RNA experiments.  Last time I tried though it wasn't well supported by the other CRAM implementations.)

**Comment by jianguozhouzunyimedicaluniversity** [comment] 2022-04-28 09:20
Dear all, thanks for your message.
I'm happy to update some issues for you. The provider shared their reference with me, so I'm trying.

The reason why they use a difference reference is explained here in case it’s of interest [https://www.sciencedirect.com/science/article/pii/S1525157822000058?via%3Dihub](https://www.sciencedirect.com/science/article/pii/S1525157822000058?via=ihub)

**Comment by jkbonfield** [comment] 2022-05-10 13:59
Closing this as it's an issue with the data that the tool is correctly identifying.  The somewhat confusing error messages have already been improved in other PRs.

Thanks for your help in diagnosing the cause of the problem and prompt replies.

**Closed by jkbonfield** 2022-05-10 13:59 UTC
