### ISSUE TITLE
Reading cram files becomes extremely slow when no reference file is provided. 

### ISSUE THREAD

**Issue by y9c** [samtools/samtools#1775] opened 2023-01-04 01:29 UTC
I wonder if samtools `view` (*also other commands*) automatically use reference file path in the header when reading CRAM files without `--reference` arg? I tried to view a CRAM with a simple command `samtools view test.cram` and it works. But it takes a very long time (~4mins) to finish for the first time. But if I specified `--reference` arg, it will be as fast as 0.2 seconds. 

What is the difference? Is it because samtools are creating some cache for reference file for the first time? But why does this not happen when `--reference` arg is given. 

I am also curious why we need to parse the reference for every command. If I just want to count records number, say `samtools view -c`, why the program still try to parse reference first?

**Comment by jkbonfield** [comment] 2023-01-04 09:17
Please see http://www.htslib.org/doc/samtools.html#REFERENCE_SEQUENCES for the details on how the reference sequences work for htslib and CRAM.

To answer the question - if you give samtools a `--reference` file then it believes you're not trying to do something silly and it uses that as the reference, therefore it has it already and it can start decoding instantly.  If it didn't supply a reference, then it needs to find it somehow.  It tries a variety of methods, but if none of the ways of finding one locally work then it goes to the internet and downloads it from the EBI via the refget API.  It should cache this locally so the next time it's fast again.

The fastest way of handling references however is to take your fasta files and process them with the `seq_cache_populate.pl` perl script.  See http://www.htslib.org/doc/samtools.html#ENVIRONMENT_VARIABLES for more details.  This produces one file per reference sequence, named after its md5sum.  CRAM will then match the SQ M5 tag to this.  The speed up here over traditional fasta is that all the whitespace has been removed already and we can simply do direct random access into the file (usually via the `mmap` system call, to make it appear to be memory).

For the last question, the CRAM format offers too much flexibility.  The earliest CRAMs produced by cramtools.jar and some versions of scramble mixed multiple types of data together in a CRAM block.   An example in SAM could be "I want to know POS field, but POS and MQUAL" are always stored together so I have to read both.   CRAM is totally flexible in what gets stored where, so even just counting the number of records may mean decoding any part of CRAM, especially given `view -c` can be used with filtering options.  Technically it could just ignore the reference and decode the wrong bases, as we know the count will be throwing them away again after decode, but the library isn't written that way.  It can't decode something wrongly - it's either correct or not at all.  Hence the reference is needed for all operations as there is no way to know ahead of time whether or not it is needed.

That's the history anyway.  In reality all modern CRAMs separate all data fields into their own blocks, permitting much better random access and data-type based filtering / access, but the library cannot guarantee how the CRAM has been encoded so it doesn't make assumptions.

I'm sure however there is room for improvement here, with delayed reference loading.

**Comment by y9c** [comment] 2023-01-04 09:30
Thank you very much for the clear explanations.

**Comment by jkbonfield** [comment] 2023-01-04 09:33
I will take a look at view -c though.  It does appear we could be giving it better hints.  Certainly `samtools fastq` has the logic already to state which fields it needs to decode so I'm surprised `view -c` doesn't.  If it's easy to do it may make a nice starter to the new year!  Thanks for the question.

**Comment by y9c** [comment] 2023-01-04 09:41
I read the document carefully but still can not understand the logic of this one

> It tries a variety of methods, but if none of the ways of finding one locally work


I have a CRAM file, and try to open it with samtools view. I checked the UR tag, and the file path is correct. I have r+w access to the file. But the message is as follow if I try to read it for the first time:

```
[I::cram_populate_ref] Running cram_populate_ref on fd 0x562d20251e20, id 0
[I::cram_populate_ref] Populating local cache: /home/debug1/.cache/hts-ref/%2s/%2s/%s
[I::cram_populate_ref] Querying ref db9bc24dfc44fdfa8a1e603465a35ca2
[D::init_add_plugin] Loaded "mem"
[D::init_add_plugin] Loaded "crypt4gh-needed"
[D::init_add_plugin] Loaded "libcurl"
[D::init_add_plugin] Loaded "gcs"
[D::init_add_plugin] Loaded "s3"
[D::init_add_plugin] Loaded "s3w"

```


It seem that it download the file from aws server again?

**Comment by y9c** [comment] 2023-01-04 10:03
It would be extremely helpful if some tools could skip the base decoding process. I suppose for higher performance CPU and most of the command in samtools, IO speed rather than the CPU would be the bottleneck. I am not sure if my guess is correct. CRAM files are reduced in size (~10x) to SAM format, so they might be some speedup for some commands. However, when I replaced all the intermediate files in some of my pipelines, the speed significantly decreased. 

BTW, besides `samtools view -c`, `samtools sort` and `samtools merge` also do not need to decode the reference file for most of the case, am I correct?

**Comment by y9c** [comment] 2023-01-04 10:13
Will adding a flag to specific CRAM file version be a good solution to this problem, while maintaining backward compatibility at the same time.

**Comment by jkbonfield** [comment] 2023-01-04 10:26
You can use strace to see what it's doing.  My local test file has SQ headers like this:

```
@SQ	SN:hs37d5	LN:35477943	M5:5b6a4b3a81a2d3c134b7d14bf6ad39f1	UR:/nfs/srpipe_references/references/Human/1000Genomes_hs37d5/all/fasta/hs37d5.fa
```

So I can then strace for a few specific file system calls to see it querying the file:

```
$ REF_CACHE=/missing REF_PATH=/non-existant strace -f -e 'trace=stat,access,open,openat' samtools116 view --verbosity 11 -c ~/scratch/data/novaseq.10m.cram 2>&1
[...trimmed...]
[I::cram_populate_ref] Running cram_populate_ref on fd 0x55773a590430, id 0
[I::cram_populate_ref] Querying ref 1b22b98cdeb4a9304cb5d48026a85128
stat("/missing/1b22b98cdeb4a9304cb5d48026a85128", 0x7ffed1103340) = -1 ENOENT (No such file or directory)
stat("/non-existant/1b22b98cdeb4a9304cb5d48026a85128", 0x7ffed11021d0) = -1 ENOENT (No such file or directory)
stat("1b22b98cdeb4a9304cb5d48026a85128", 0x7ffed11021d0) = -1 ENOENT (No such file or directory)
access("/nfs/srpipe_references/references/Human/1000Genomes_hs37d5/all/fasta/hs37d5.fa.fai", R_OK) = 0
openat(AT_FDCWD, "/nfs/srpipe_references/references/Human/1000Genomes_hs37d5/all/fasta/hs37d5.fa", O_RDONLY) = 4
openat(AT_FDCWD, "/nfs/srpipe_references/references/Human/1000Genomes_hs37d5/all/fasta/hs37d5.fa.fai", O_RDONLY) = 5
access("/nfs/srpipe_references/references/Human/1000Genomes_hs37d5/all/fasta/hs37d5.fa.fai", R_OK) = 0
openat(AT_FDCWD, "/nfs/srpipe_references/references/Human/1000Genomes_hs37d5/all/fasta/hs37d5.fa", O_RDONLY) = 4
```

So I see it hunting in REF_CACHE, then REF_PATH, then the UR filename which it found and loaded.  This may help diagnose why it's failing to fetch your local reference.

Regarding other subcommands, correct there are clearly more tools which could avoid using the reference.  I'd forgotten the details of how the reference loading worked before (it's overly complex!), and see it already does only load on demand.  We have a mechanism to give hints to the CRAM code for which SAM columns need populating.  This is controlled in the code via the CRAM_OPT_REQUIRED_FIELDS parameter.  Eg from `samtools stat` code it has:

```
    if (hts_set_opt(fp, CRAM_OPT_REQUIRED_FIELDS,
                    SAM_FLAG | SAM_MAPQ | SAM_RNEXT)) {
        fprintf(stderr, "Failed to set CRAM_OPT_REQUIRED_FIELDS value\n");
        return 1;
    }
```

I'm not entirely sure why more than `SAM_FLAG` is in there, but it's likely to do with how some of the flags are stored in CRAM as it's not a perfect 1:1 mapping.

I *thought* I'd gone through all the samtools subcommands adding appropriate logic to each of them to speed things up, but I see that I apparently did not. :(

Note however that sort and merge cannot be trivially changed.  At least not yet.  The reason is that flagstats is just producing a summary output statistic, as is `view -c`.  However merge and sort are producing actual SAM/BAM/CRAM files.  If we don't decode all the data, then the file we output will be incomplete.   Ideally we'd avoid decoding CRAM and then reencoding exactly the same data again and would short-cut that step if we know the output hasn't changed (this is a long term goal).  However even that won't work with sort/merge as the data is changing order.  So we do have to fully decode, juggle the data around a bit, and then fully reencode.  So unfortunately we cannot do the same trick.

The good news is that we can simulate some of `samtools flagstat` speedups already using `samtools view --input-fmt-option`.  For example observe these benchmarks:

```
# BAM
$ perf stat -e cycles samtools116 view -c -F 0x40 ~/scratch/data/novaseq.10m.bam 1:20m-40m
2093436
 Performance counter stats for 'samtools116 view -c -F 0x40 /nfs/users/nfs_j/jkb/scratch/data/novaseq.10m.bam 1:20m-40m':
        8103611334      cycles                                                      
       2.712773053 seconds time elapsed

# CRAM, no options:
 Performance counter stats for 'samtools116 view -c -F 0x40 /nfs/users/nfs_j/jkb/scratch/data/novaseq.10m.cram 1:20m-40m':
       24510417012      cycles                                                      
       8.205125227 seconds time elapsed

# CRAM, with --input-fmt-option required_fields=0x1c (FLAG, POS, MAPQ)
 Performance counter stats for 'samtools116 view -c -F 0x40 --input-fmt-option required_fields=0x1c /nfs/users/nfs_j/jkb/scratch/data/novaseq.10m.cram 1:20m-40m':
        4683406028      cycles                                                      
       1.604673832 seconds time elapsed
```

So by standard usage, this CRAM is 3x slower than BAM.  By manually restricting which fields we decoded from CRAM, it becomes 70% faster than BAM (over 5x quicker than the earlier CRAM usage).  This clearly shows we should be checking the samtools view options and creating an appropriate set of fields to decode based on the various view command line filtering options.

The 0x1c comes from this bit-field defined in htslib/hts.h

```
// REQUIRED_FIELDS
enum sam_fields {
    SAM_QNAME = 0x00000001,
    SAM_FLAG  = 0x00000002,
    SAM_RNAME = 0x00000004,
    SAM_POS   = 0x00000008,
    SAM_MAPQ  = 0x00000010,
    SAM_CIGAR = 0x00000020,
    SAM_RNEXT = 0x00000040,
    SAM_PNEXT = 0x00000080,
    SAM_TLEN  = 0x00000100,
    SAM_SEQ   = 0x00000200,
    SAM_QUAL  = 0x00000400,
    SAM_AUX   = 0x00000800,
    SAM_RGAUX = 0x00001000,
};
```

I am therefore working on a PR to improve this and make view -c automatically select the necessary options.

**Comment by jkbonfield** [comment] 2023-01-04 10:35
One other thought occurs here too.  It's a bit ghastly though.

In CRAM the sequence is essentially a set of edits to the reference.  So if we had

```
REF: AGCTTATAGGCGAGATC
SEQ: AGCATATAGGCGAGATC
```

Then we would store a code indicating that the 4th base changed from T to A and that's all we need to regenerate that sequence.  Now if we're doing something like `samtools view in.cram -o out.cram` then we're loading the CRAM records into memory, decoding them to full sequence, sorting, and then reencoding back to CRAM.  Theoretically, the internal sequence could just be e.g. `===A=============`.   If we output to SAM/BAM this would change things, but outputting to CRAM would be able to regenerate the same data.

This is messy, and rather a big change for htslib, but theoretically doable.  Something for me to think about anyway.  I'm not really sure how much it would save either.

**Comment by jkbonfield** [comment] 2023-01-04 11:22
> It would be extremely helpful if some tools could skip the base decoding process. I suppose for higher performance CPU and most of the command in samtools, IO speed rather than the CPU would be the bottleneck. I am not sure if my guess is correct. CRAM files are reduced in size (~10x) to SAM format, so they might be some speedup for some commands. However, when I replaced all the intermediate files in some of my pipelines, the speed significantly decreased.

Note it's also possible to use a slightly larger non-reference based CRAM.  This can be useful in some scenarios, particularly when working in name sorted data (as the reference causes a large amount of memory thrashing and is bad for CPU cache).  That's done with e.g. `-O cram,no_ref`.  For position sorted data there are also some options to use embedded references, and with the latest code also on-the-fly consensus generation and embedding, which removes the need for using an external reference.  These aren't an ideal format for final at-rest data, but may be useful within a pipeline.   Locally we sometimes use level-1 BAM within pipelines as it's fast and "good enough" for temporary data, or if we can get away with pipes between tools then uncompressed BAM is optimal.

**Comment by jkbonfield** [comment] 2023-01-04 11:23
> It would be extremely helpful if some tools could skip the base decoding process. I suppose for higher performance CPU and most of the command in samtools, IO speed rather than the CPU would be the bottleneck. I am not sure if my guess is correct. CRAM files are reduced in size (~10x) to SAM format, so they might be some speedup for some commands. However, when I replaced all the intermediate files in some of my pipelines, the speed significantly decreased.

Note it's also possible to use a slightly larger non-reference based CRAM.  This can be useful in some scenarios, particularly when working in name sorted data (as the reference causes a large amount of memory thrashing and is bad for CPU cache).  That's done with e.g. `-O cram,no_ref`.  For position sorted data there are also some options to use embedded references, and with the latest code also on-the-fly consensus generation and embedding, which removes the need for using an external reference.  These aren't an ideal format for final at-rest data, but may be useful within a pipeline.   Locally we sometimes use level-1 BAM within pipelines as it's fast and "good enough" for temporary data, or if we can get away with pipes between tools then uncompressed BAM is optimal.

**Comment by y9c** [comment] 2023-01-04 21:57
Thank you very much for the quick improvement. 

> This is messy, and rather a big change for htslib, but theoretically doable

Yes. I agree that adding special logic for CRAM format will make the htslib complicated, but there might be some big gain on speed. 

We use samtools heavily after read mapping and before mutation calling step, including filtering reads, merge samples, drop duplicates ... We do not need sequence information in most of the steps, and both input and output format are CRAM, which can speed up IO and save storage. If the htslib can fill seqeuence with null value, such as `===A=============` you have mentioned, or directly copy the mutation code into the output file, it can save a lot of time.

**Comment by y9c** [comment] 2023-01-13 07:13
Hi @jkbonfield,

I think I have found out the cause why samtools cannot load the fasta file for cram file in my server. 
I put the fasta file under a folder symbolic linked folder and it seems that samtools cannot parse symbolic path correctly.

For example, the fasta file (ref.fa) in under `~/reference` path, where `reference` is the symbolic link to `/data/reference` and `/data` is a mounted partition. When start samtools with CRAM file input, the UR tag is point to `/home/user/reference/ref.fa`, but samtools might not think there is a file, and try to download the file remotely.

**Comment by jkbonfield** [comment] 2023-01-16 14:16
Samtools shouldn't care about whether it's a symbolic link or a directory.  It's likely something system related, such as running on a machine where your home directory isn't visible and/or the /data directory, or some related issue.

One way to debug such things is using strace.  See https://github.com/samtools/samtools/issues/1775#issuecomment-1370745248 for instructions.

You will then be able to see if samtools looked at the reference, and if it did and failed, what the failure was.

**Comment by jkbonfield** [comment] 2023-01-24 15:25
https://github.com/samtools/samtools/pull/1776 speeds up view -c (merged in develop, but not in a release yet).
This should mean that view -c (in the naive fashion of no other filtering rules) now works without needing a reference.

However it doesn't speed up reference fetching generally.   That's often simply at the whim of the EBI reference server.  All I can suggest there is you download it before hand and cache one locally.

**Closed by jkbonfield** 2023-01-24 15:25 UTC

**Comment by y9c** [comment] 2023-02-13 23:12
Thank you @jkbonfield . I got this error message when compile htslib and samtools using the lastest source code.

```
cram_size.c:59:19: error: ‘CRAM_COMP_RAW’ undeclared here (not in a function); did you mean ‘CRAM_OPT_RANGE’?
     COMP_RAW    = CRAM_COMP_RAW,
                   ^~~~~~~~~~~~~
```

I think it might relative to this update?

**Comment by jkbonfield** [comment] 2023-02-14 08:59
Yes it's caused by using the develop version of samtools, however this definition is in the develop version of htslib.  You'll need to update both if you want to stick with the bleeding edge.

**Comment by y9c** [comment] 2023-02-14 09:01
Yes. I have also pull the latest version of htslib.

**Comment by jkbonfield** [comment] 2023-02-14 09:07
In that case you need to carefully look at your samtools configure output (and maybe look at the compilation command lines or config.h).  It's almost certainly picked up and found an old htslib from somewhere else.  Where is your htslib clone in relation to the samtools one?

The latest htslib most definitely does [expose this symbol](https://github.com/samtools/htslib/blob/develop/htslib/cram.h#L88).

**Comment by y9c** [comment] 2023-02-14 09:11
thank you for the suggestion. I put htslib in the same level of samtools. I also tried to specify the path by with htslib argument. But also don't work.

**Comment by jkbonfield** [comment] 2023-02-14 09:18
Along side samtools, as a sibling directory, ought to be OK.

Your config.mk file should contain `HTSLIB_CPPFLAGS` detailing where it's found your copy of htslib to use (although possibly this may be empty if it's using a system installed one).  

config.log will also contain lines explaining where it found htslib. Eg:

```
configure:3524: checking location of HTSlib source tree
configure:3545: result: ../htslib
```

Plus make sure you do use configure, and `autoreconf -i` on both directories to rebuild the configure scripts too as they may have updated since you last did a git pull. (See "Building Configure" in INSTALL)

**Comment by y9c** [comment] 2023-02-14 09:22
Thank you. More details are as follow:

```
$ grep HTSLIB_CPPFLAGS config.mk
HTSLIB_CPPFLAGS = -I../htslib

$ cd ../htslib && cat version.h

#define HTS_VERSION_TEXT "1.16-54-gf68c84f"

```

**Comment by whitwham** [comment] 2023-02-14 09:24
I have just tried compiling with new git clones of htslib and samtools.  It all worked for me.

**Comment by y9c** [comment] 2023-02-14 09:27
Yes. This is the first time I have had this problem. I used to combine samtools from source and works. If I check out branch cfded157e04fe04cdab96a0f771df9257d8a42d3, it also can be compiled.

**Comment by y9c** [comment] 2023-02-14 09:32
Sorry for the mistake. I might find the cause. In order to include ncursesw, I add `CFLAGS=-I${LIB_PATH}/include` in the configure step, so in the compiling step, the command because `gcc -Wall -I/home/y9c/.local/include -I. -I../htslib -I./lz4  -c -o cram_size.o cram_size.c`, and another htslib overwrite the lastest one.

**Comment by jkbonfield** [comment] 2023-02-14 09:33
Hmm, what is `-I/home/y9c/.local/include` and where did that come from?  For that matter, can you do `which gcc` please?

If this is conda I'm going to sigh. lol.

**Comment by y9c** [comment] 2023-02-14 09:35
Yes. 
```
$ which gcc
/usr/bin/gcc
```

**Comment by jkbonfield** [comment] 2023-02-14 09:39
And your ~/.local/include dir?

What about:

```
find ~/.local/include -name cram.h
```

Your gcc command line has this directory before the ../htslib one, so if you find an older version there it will be used.   I'm not sure where it comes from.  Again, check your config.log file - it tells you everything you need to know.  It may also be worth checking your environment.  Eg `printenv | fgrep .local`.  Maybe you have CPATH or C_INCLUDE_PATH defined.

It would be helpful in future to report the full error messages, including things like command lines, as the cause would have been diagnosed much quicker.

**Comment by jkbonfield** [comment] 2023-02-14 09:42
Finally, if you're struggling to work out what's really going on with includes, just do a "gcc -E" and grep.  Eg the command make executed was `gcc -Wall -I/home/y9c/.local/include -I. -I../htslib -I./lz4  -c -o cram_size.o cram_size.c`, so turn that into `gcc -Wall -I/home/y9c/.local/include -I. -I../htslib -I./lz4  -E cram_size.c | fgrep cram.h` and you'll see where the compiler is finding the header file from.

**Comment by y9c** [comment] 2023-02-14 09:43
`ls ~/.local/include |grep cram` do not return any file. But found that there are htslib.so file under `.local/lib/libhts.so`. After removing that, the compile works smoothly.

**Comment by y9c** [comment] 2023-02-14 09:44
Thank you very much for your help.

**Comment by jkbonfield** [comment] 2023-02-14 10:07
Do you know how it got there, or also why .local is even in your compilation lines?

This smells like some tool editing your ~/.bashrc or ~/.bash_profile scripts for you and breaking your environment.

Best advice I have there is to always edit them back again!  I tend to make aliases or shell functions that do the same, so I can invoke the configuration as the tool wanted, but not permanently on in my environment.  Eg I don't have conda at all until I type "go_conda", at which point it's set up, but only then.  It helps avoid all sorts of bizarre bugs like this.

**Comment by y9c** [comment] 2023-02-14 10:12
Yes. I use conda environment and it messes up a lot of things in my environment. Thank you for the good suggestion. I will check and avoid conda changing the default settings.

**Comment by jkbonfield** [comment] 2023-02-14 10:17
> Yes. I use conda environment and it messes up a lot of things in my environment. Thank you for the good suggestion. I will check and avoid conda changing the default settings.

I'm thinking of the classic "When I do <this> it hurts", "Well, don't do <that> then!" comedy.  Conda needs to be carefully sandboxed away in its own little environment.  It simply causes too many problems with building third party software that's not part of the Conda ecosystem.

At least we know the cause.  Thanks.
