### ISSUE TITLE
HTSlib components are not called

### ISSUE THREAD

**Issue by PlatonB** [samtools/samtools#1157] opened 2019-12-20 15:15 UTC
elementary OS 5.1
samtools 1.10
Using htslib 1.10

Unlike 1.9, in 1.10 it is not possible to call HTSlib components.

`export PATH=/home/platon/Загрузки/samtools/bin/:$PATH`
`bgzip`
Command 'bgzip' not found, but can be installed with

`tabix`
Command 'tabix' not found, but can be installed with

Do I now need to install HTSlib manually? If so, please update the documentation.

**Comment by jmarshall** [comment] 2019-12-20 15:22
I am unaware of this having changed from previous versions. Perhaps previously you had in fact installed HTSlib separately or as below?

From samtools's _INSTALL_ file:

> (If you have not also installed HTSlib separately, you may wish to install the bgzip, htsfile, and tabix utilities from the associated copy of HTSlib. Type 'make install install-htslib' to do this.)

**Comment by PlatonB** [comment] 2019-12-20 15:30
> Perhaps previously you had in fact installed HTSlib separately or as below?

Earlier, I did not install HTSlib explicitly. But its components worked.

> Type 'make install install-htslib' to do this.

Thanks, this solves the problem.

**Comment by jkbonfield** [comment] 2020-01-02 09:43
It's possible it worked before due to finding them somewhere else.  As @jmarshall points out this hasn't changed and it's been this way for some time.  Closing as it's not a bug.

**Closed by jkbonfield** 2020-01-02 09:43 UTC
