### ISSUE TITLE
index: samtools index error for inclusion of out.index is misleading

### ISSUE THREAD

**Issue by kortschak** [samtools/samtools#400] opened 2015-06-01 23:15 UTC
Currently, if the usage message for `samtools index` is trusted the invocation aborts with "Samtools-htslib-API: bam_index_build2() not yet implemented".

Either the usage should be changed so that it does not refer to an optional <out.index> outfile or the error string should be fixed.

**Comment by jmarshall** [comment] 2015-06-02 07:29
Duplicate of #199.

**Closed by jmarshall** 2015-06-02 07:29 UTC
Labels: duplicate
