### ISSUE TITLE
samtools quickcheck fails to detect missing EOF in a bam file

### ISSUE THREAD

**Issue by bsigurjonsson** [samtools/samtools#1884] opened 2023-07-19 17:25 UTC
Running samtools 1.17
OS:  Darwin 22.4.0
arm64

gcc --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Steps to reproduce**

1. DL a bam & bai file from http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwRepliSeq/ (wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam)
2. ls -lh to see it is 64K size
3. Truncate it: `truncate -s 60K wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam`
4. `samtools quickcheck wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam` and there is no error
5. `samtools view wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam | wc -l` and you get [W::bam_hdr_read] EOF marker is absent

**Comment by jmarshall** [comment] 2023-07-20 10:47
I've attempted to reproduce this on macOS (arm64 Darwin 22.5.0, much like the OP's environment).

I'm a bit confused because the _wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam_ I downloaded from the specified location is 92M, not 64K.

But nonetheless I truncated it with `truncate -s 64k` and `truncate -s 60k` and attempted to reproduce the problem. However for me `quickcheck` produced the expected messages:

```
$ ls -lh wg*.bam
-rw-r--r--  1 johnm  staff    60K 20 Jul 21:36 wgEncode60K.bam
-rw-r--r--  1 johnm  staff    64K 20 Jul 21:34 wgEncode64K.bam
-rw-r--r--  1 johnm  staff    92M 18 Feb  2011 wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam
$ samtools-1.17 quickcheck wg*.bam
wgEncode60K.bam was missing EOF block when one should be present.
wgEncode64K.bam was missing EOF block when one should be present.
$ samtools quickcheck wg*.bam     # 1.17-36-g03124db+htslib-1.17-59-ga809db7
wgEncode60K.bam was missing EOF block when one should be present.
wgEncode64K.bam was missing EOF block when one should be present.
```

**Comment by bsigurjonsson** [comment] 2023-07-20 11:48
Ahh interesting, yes when I re download the file (all 92mb) the quickcheck works after i truncate.
But interestingly the issue remains with the 64K bam, probably some failed download from my browser:

[wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam.gz](https://github.com/samtools/samtools/files/12105641/wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam.gz)

```
gunzip wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam.gz
samtools quickcheck wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam # does not complain
samtools view wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam # EOF error
```

**Comment by jmarshall** [comment] 2023-07-20 11:59
What does `htsfile` say about this file?

If it's a partial download via a browser, you may have run into samtools/hts-specs#734.

**Comment by bsigurjonsson** [comment] 2023-07-20 12:17
```
htsfile wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam                                                                                                                                 
wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam:	BAM version 1 sequence data
```

**Comment by jmarshall** [comment] 2023-07-20 12:24
And plain `file` instead of `htsfile`? I was hoping that would report on the file's compression status, but perhaps it does not.

**Comment by bsigurjonsson** [comment] 2023-07-20 12:26
```
file wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam                                                                                                                                    
wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam: SAMtools BAM (Binary Sequence Alignment/Map)
```

**Comment by daviesrob** [comment] 2023-07-20 12:31
Indeed, it may be a case of samtools/hts-specs#734
```
$ hd /tmp/wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam | head
00000000  42 41 4d 01 00 00 00 00  18 00 00 00 05 00 00 00  |BAM.............|
00000010  63 68 72 31 00 3d 43 db  0e 05 00 00 00 63 68 72  |chr1.=C......chr|
00000020  32 00 8d ed 7e 0e 05 00  00 00 63 68 72 33 00 1e  |2...~.....chr3..|
00000030  95 cd 0b 05 00 00 00 63  68 72 34 00 64 c8 64 0b  |.......chr4.d.d.|
00000040  05 00 00 00 63 68 72 35  00 3c 8c c8 0a 05 00 00  |....chr5.<......|
00000050  00 63 68 72 36 00 3b 02  33 0a 05 00 00 00 63 68  |.chr6.;.3.....ch|
00000060  72 37 00 67 43 7c 09 05  00 00 00 63 68 72 38 00  |r7.gC|.....chr8.|
00000070  76 56 b9 08 05 00 00 00  63 68 72 39 00 f7 be 6a  |vV......chr9...j|
00000080  08 06 00 00 00 63 68 72  31 30 00 9b 18 14 08 06  |.....chr10......|
00000090  00 00 00 63 68 72 31 31  00 34 09 0c 08 06 00 00  |...chr11.4......|
```

No sign of a BGZF wrapper there, so also no EOF block for `samtools quickcheck` to find.  Possibly if should warn about unwrapped BAMs.

**Comment by jmarshall** [comment] 2023-07-21 11:03
It turns out the `htsfile` output above **did** identify the BAM file as pre-decompressed, by reporting “BAM version 1 sequence data” — in particular, omitting “compressed” from the description. However in isolation this is not particularly obvious; PR samtools/htslib#1656 improves the report to explicitly include “uncompressed”.

I have now tried downloading the BAM file with Safari rather than curl, as I did previously. Downloading via Safari also produces a pre-decompressed file of exactly 64K. It happens that the first BGZF block of this file is 64K uncompressed… I wonder if all these web browsers are downloading only one concatenated gzip stream out of a download (presumably as a security measure or something)… 🤔

**Comment by daviesrob** [comment] 2023-07-26 10:34
Closing as this mostly looks like a website configuration problem.  Meanwhile, I note that quickcheck does give the game away if you turn its verbosity up:

```
$ ./samtools quickcheck -vvv /tmp/wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam
verbosity set to 3
checking /tmp/wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam
opened /tmp/wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam
/tmp/wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam is sequence data
/tmp/wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam has 24 targets in header.
/tmp/wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam cannot be checked for EOF block because its filetype does not contain one.
```

It might be worth making quickcheck reject BAM files without a BGZF wrapper, but otherwise there's not much it could do to spot this problem.  (We would still want to be able to read such files though, as they're useful for testing purposes.)

**Closed by daviesrob** 2023-07-26 10:34 UTC
