### ISSUE TITLE
NM value different between samtools 1.3.1 and samtools 1.5 when going to CRAM

### ISSUE THREAD

**Issue by jsotobroad** [samtools/samtools#717] opened 2017-08-23 21:52 UTC
[small.sam.txt](https://github.com/samtools/samtools/files/1247148/small.sam.txt)
I was trying to test the latest version of samtools but the bam i was creating from my cram was not validating with Picards ValidateSamFile tool.

Attached I have a sam file that I converted to cram with samtools and then viewed that cram with samtools and they gave me different NM values.  These are the outputs when I run `samtools view` on the resulting cram.  (all of these steps were run independently for each samtools version)

Commands run:
`samtools view -C -T Homo_sapiens_assembly38.fasta -o st_{samtools_version}.cram small.sam`
`samtools view st_{samtools_version}.cram`

1.3.1:
```
HK3T5CCXX160204:3:2209:1377:28804	163	chr1	10000	0	91M60S	=	10391	470	NTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAGCCCTAACCCTAACCCTAACCCCAGCCCTAACCCTAACCCTAGCCCTAACCCCCACCCCAACCCCTACCCCCCACCCTCACCCCCCCCCCGCGCCCTCACACCCACCCCCCC	#?????????????????????????????????????5??????????????????????55'????+5555??55???++???5++???+555??+5+5???###############################################	MC:Z:75S26M5D37M1I11M1S	MQ:i:0	AS:i:70	MD:Z:39A21T1A17A9	NM:i:4	RG:Z:HK3T5.3
HK3T5CCXX160204:3:2209:1377:28804	83	chr1	10391	0	75S26M5D37M1I11M1S	=	10000	-470	CCCTAGCCCTACCCCTCCCCCCCACCCCCAACCCCCCCCCTCACCCCTCACCCTCCCCCCCCCCCCCCACCCCCGCCCTAACCCCTAACCCTCGCCCTAACCCCTAACCCTCGCCCTAACCCCTAACCCTCGCCCTAACCCCTAACCCTCN	#####################################################################???&555??++5????5++5??+5&?'?+5????????????5??????????????????????????????????????#	MC:Z:91M60S	MQ:i:0	AS:i:26	MD:Z:17A0A7^CCTAA10A0A17A0A17	NM:i:12	RG:Z:HK3T5.3
```

1.5
```
HK3T5CCXX160204:3:2209:1377:28804	163	chr1	10000	0	91M60S	=	10391	470	NTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAGCCCTAACCCTAACCCTAACCCCAGCCCTAACCCTAACCCTAGCCCTAACCCCCACCCCAACCCCTACCCCCCACCCTCACCCCCCCCCCGCGCCCTCACACCCACCCCCCC	#?????????????????????????????????????5??????????????????????55'????+5555??55???++???5++???+555??+5+5???###############################################	MC:Z:75S26M5D37M1I11M1S	MQ:i:0	AS:i:70	MD:Z:0N38A21T1A17A9	NM:i:5	RG:Z:HK3T5.3
HK3T5CCXX160204:3:2209:1377:28804	83	chr1	10391	0	75S26M5D37M1I11M1S	=	10000	-470	CCCTAGCCCTACCCCTCCCCCCCACCCCCAACCCCCCCCCTCACCCCTCACCCTCCCCCCCCCCCCCCACCCCCGCCCTAACCCCTAACCCTCGCCCTAACCCCTAACCCTCGCCCTAACCCCTAACCCTCGCCCTAACCCCTAACCCTCN	#####################################################################???&555??++5????5++5??+5&?'?+5????????????5??????????????????????????????????????#	MC:Z:91M60S	MQ:i:0	AS:i:26	MD:Z:17A0A7^CCTAA10A0A17A0A17	NM:i:12	RG:Z:HK3T5.3
```

When I try to validate the output of 1.5 with Picard ValidateSamFile I get this error - `ERROR: Record 17, Read name HK3T5CCXX160204:3:2209:1377:28804, NM tag (nucleotide differences) in file [5] does not match reality [4]` whereas with the output of 1.3.1 it validates.

Here is a list of validation errors I received when trying to validate a bam created from samtools 1.5 which makes it look like an off by one error
```
ERROR: Record 17, Read name HK3T5CCXX160204:3:2209:1377:28804, NM tag (nucleotide differences) in file [5] does not match reality [4]
ERROR: Record 18, Read name HK3T5CCXX160204:5:2204:7131:43448, NM tag (nucleotide differences) in file [1] does not match reality [0]
ERROR: Record 71801428, Read name HJYFJCCXX160204:5:1217:2503:72561, NM tag (nucleotide differences) in file [13] does not match reality [12]
ERROR: Record 71802933, Read name HK3T5CCXX160204:3:2105:1357:42763, NM tag (nucleotide differences) in file [8] does not match reality [7]
ERROR: Record 71806876, Read name HJYFJCCXX160204:8:1121:6441:72420, NM tag (nucleotide differences) in file [11] does not match reality [10]
ERROR: Record 71807035, Read name HK35MCCXX160204:1:1114:1316:18924, NM tag (nucleotide differences) in file [13] does not match reality [12]
ERROR: Record 71811866, Read name HJYFJCCXX160204:5:2106:1773:72455, NM tag (nucleotide differences) in file [15] does not match reality [14]
ERROR: Record 71828750, Read name HJYFJCCXX160204:6:1219:1397:68183, NM tag (nucleotide differences) in file [24] does not match reality [23]
ERROR: Record 71828873, Read name HJYFJCCXX160204:6:2121:1671:61239, NM tag (nucleotide differences) in file [16] does not match reality [15]
ERROR: Record 71840836, Read name HJYFJCCXX160204:6:2121:1600:62839, NM tag (nucleotide differences) in file [22] does not match reality [21]
ERROR: Record 71843471, Read name HJYFJCCXX160204:6:1202:27773:72596, NM tag (nucleotide differences) in file [11] does not match reality [10]
ERROR: Record 71850825, Read name HJYFJCCXX160204:8:2219:32207:72684, NM tag (nucleotide differences) in file [31] does not match reality [30]
ERROR: Record 71861756, Read name HK35NCCXX160204:2:1108:1164:64966, NM tag (nucleotide differences) in file [25] does not match reality [24]
ERROR: Record 71895242, Read name HJYFJCCXX160204:5:2217:1692:58708, NM tag (nucleotide differences) in file [14] does not match reality [13]
ERROR: Record 71916594, Read name HJYFJCCXX160204:6:2204:31872:45312, NM tag (nucleotide differences) in file [4] does not match reality [3]
ERROR: Record 147016128, Read name HJYFJCCXX160204:4:1210:3914:72754, NM tag (nucleotide differences) in file [8] does not match reality [7]
ERROR: Record 147016246, Read name HJYFJCCXX160204:5:2213:1692:37436, NM tag (nucleotide differences) in file [9] does not match reality [8]
ERROR: Record 147016320, Read name HJYFJCCXX160204:6:2109:18304:72684, NM tag (nucleotide differences) in file [19] does not match reality [18]
ERROR: Record 147016373, Read name HJYFJCCXX160204:7:1208:1194:22124, NM tag (nucleotide differences) in file [13] does not match reality [12]
ERROR: Record 147016479, Read name HJYFJCCXX160204:8:2201:1702:62874, NM tag (nucleotide differences) in file [12] does not match reality [11]
ERROR: Record 147016495, Read name HJYFJCCXX160204:8:2216:1438:62874, NM tag (nucleotide differences) in file [9] does not match reality [8]
ERROR: Record 147016941, Read name HK35MCCXX160204:5:2204:1448:55403, NM tag (nucleotide differences) in file [16] does not match reality [15]
ERROR: Record 147017157, Read name HK35MCCXX160204:8:2120:32563:46156, NM tag (nucleotide differences) in file [16] does not match reality [15]
ERROR: Record 147017299, Read name HK35NCCXX160204:2:2108:32644:48547, NM tag (nucleotide differences) in file [9] does not match reality [8]
ERROR: Record 147017734, Read name HK3T5CCXX160204:5:2212:23165:1256, NM tag (nucleotide differences) in file [13] does not match reality [12]
ERROR: Record 147017820, Read name HK3T5CCXX160204:7:1202:15463:1415, NM tag (nucleotide differences) in file [16] does not match reality [15]
ERROR: Record 147018163, Read name HJYFJCCXX160204:7:2214:32644:51605, NM tag (nucleotide differences) in file [9] does not match reality [8]
ERROR: Record 147019084, Read name HJYFJCCXX160204:4:1101:17848:73053, NM tag (nucleotide differences) in file [4] does not match reality [3]
ERROR: Record 147019085, Read name HJYFJCCXX160204:4:1101:17898:72965, NM tag (nucleotide differences) in file [4] does not match reality [3]
ERROR: Record 147019948, Read name HJYFJCCXX160204:4:1207:1387:64580, NM tag (nucleotide differences) in file [14] does not match reality [13]
ERROR: Record 147020160, Read name HJYFJCCXX160204:4:1213:6360:72912, NM tag (nucleotide differences) in file [16] does not match reality [15]
ERROR: Record 147023019, Read name HJYFJCCXX160204:5:1212:2575:72614, NM tag (nucleotide differences) in file [18] does not match reality [17]
ERROR: Record 147025498, Read name HJYFJCCXX160204:6:1202:1519:22194, NM tag (nucleotide differences) in file [9] does not match reality [8]
ERROR: Record 147025538, Read name HJYFJCCXX160204:6:1203:1489:62505, NM tag (nucleotide differences) in file [8] does not match reality [7]
ERROR: Record 147026545, Read name HJYFJCCXX160204:6:2112:1722:22757, NM tag (nucleotide differences) in file [12] does not match reality [11]
ERROR: Record 147027388, Read name HJYFJCCXX160204:6:2219:11475:72701, NM tag (nucleotide differences) in file [10] does not match reality [9]
ERROR: Record 147030254, Read name HJYFJCCXX160204:7:2222:1529:63103, NM tag (nucleotide differences) in file [5] does not match reality [4]
ERROR: Record 147031768, Read name HJYFJCCXX160204:8:1224:12205:72631, NM tag (nucleotide differences) in file [15] does not match reality [14]
ERROR: Record 147036750, Read name HK35MCCXX160204:1:2117:29812:42763, NM tag (nucleotide differences) in file [14] does not match reality [13]
ERROR: Record 147039021, Read name HK35MCCXX160204:2:2106:12225:1397, NM tag (nucleotide differences) in file [18] does not match reality [17]
ERROR: Record 147055082, Read name HK35MCCXX160204:8:2217:29153:69256, NM tag (nucleotide differences) in file [7] does not match reality [6]
ERROR: Record 147057548, Read name HK35NCCXX160204:1:2207:1600:14494, NM tag (nucleotide differences) in file [19] does not match reality [18]
ERROR: Record 147060702, Read name HK3T5CCXX160204:1:1102:6756:1696, NM tag (nucleotide differences) in file [6] does not match reality [5]
ERROR: Record 147070497, Read name HK3T5CCXX160204:4:2208:4259:1168, NM tag (nucleotide differences) in file [10] does not match reality [9]
ERROR: Record 147074430, Read name HK3T5CCXX160204:6:1212:15656:1256, NM tag (nucleotide differences) in file [10] does not match reality [9]
ERROR: Record 188889207, Read name HK35MCCXX160204:3:2120:4411:13246, NM tag (nucleotide differences) in file [18] does not match reality [17]
ERROR: Record 188892986, Read name HK35MCCXX160204:3:2120:10115:64580, NM tag (nucleotide differences) in file [3] does not match reality [2]
```

Is there something I may have done wrong here?

**Comment by jkbonfield** [comment] 2017-08-25 13:04
In theory it's meant to spot when the NM tag is incorrect and store it verbatim.   Sometimes it is infact wrong due to aligner bugs, but even then it ought to be round-tripping without changing it.  I'll see if I can reproduce this.

**Comment by jsotobroad** [comment] 2017-08-25 13:46
it also seems to happen with 1.4.1

**Comment by jkbonfield** [comment] 2017-08-25 14:35
The problem is due to this commit: 4eef9a7fe5a2429550682e31c1935d5e4ef73555

I changed CRAM's  NM calculation to match the calmd one, which specifically has a bizarre statement of N vs N being mismatch.  I don't understand why, but that's why the new code counts the number of diffs as 5 instead of 4.  (The ref is also N for base 10000.)  This applies to MD calculation also.

We need to rethink this then.  I thought samtools matched picard in this behaviour, but maybe not.

**Comment by jkbonfield** [comment] 2017-08-25 14:50
Picard SetNmMdAndUqTags treats N vs N as a match, but samtools calmd does not:

https://github.com/samtools/samtools/blob/10b403702571299cb9a85333935b6d762badbb88/bam_md.c#L66

I think with hindsight fixing CRAM to be consistent with calmd was a mistake.  CRAM was correct and calmd not.  Do we know why calmd has this logic?  It appears to have been like it since day 1,  with no  explanation.

**Comment by jsotobroad** [comment] 2017-08-25 15:32
Thank you for the quick response and explanation!  There are people better than I to address your questions/suggestions to but I will guide them here hopefully leading to a conversation.

**Comment by jsotobroad** [comment] 2017-08-25 17:28
@yfarjoun @tfenne @eitanbanks  I was asked to ask you guys weigh in on this issue, thanks!

**Comment by yfarjoun** [comment] 2017-08-26 09:54
>NM: Edit distance to the reference, including ambiguous bases but excluding clipping.

Talk about an ambiguous description!

What does the spec mean by "including ambiguous bases"?

Does it mean that a R (in the read, A or G) and a A (in the reference) is considered NM=0 or NM=1?
What about R in both the read and the reference?
What about A in the read and R in the reference?

In Picard, the implementation is not symmetric, the logic being that the reads needs to be at-least as specific as the reference, but it can be more specific:

READ | REF | NM
----|----|----
R | R | 0
R | A | 1
A | R | 0
A | A | 0
N | N | 0


I would advocate that this is the right thing to do and to add this table (or a similar explanation) to the spec.

**Comment by jkbonfield** [comment] 2017-08-30 08:31
One key thing here is given the sequence + MD record we should be able to compute the reference, without having to explicitly load it.  That's the whole reason MD exists as stated in the spec: "The MD field aims to achieve SNP/indel calling without looking at the reference".  However if we consider A in read and R in reference to be a match then we cannot achieve this, therefore for MD "mismatch" has to be explicitly defined as anything that is different, rather than simply incompatible with.

NM is defined as the "edit distance to the reference" with a rather vague bit about ambiguous bases.  I agree NM itself is ambiguous in meaning.  However it makes far more sense to have NM being the count of mismatching bases listed in MD so both are computed together.

So in that regard NM and MD should be internally consistent with each other, which rules out use of a compatibility table as above.

IMO the only odd thing here is N vs N, which to me is a match!  Why it's treated as mismatch by `samtools calmd` is a mystery.  @lh3 can you recall this?  It's a while ago I know!

**Comment by yfarjoun** [comment] 2017-09-06 07:59
@jkbonfield it seems that your comment is inconsistent...you state that "it makes far more sense to have NM being the count of mismatching bases listed in MD so both are computed together" which would imply that N<->N should not be counted as a mismatch (as it wouldn't show up in the MD string) but then state that " non ACGT base in the reference must be considered as a mismatch, not just N." which implies that the NM will not be the sum of the mismatching bases in MD. 

I guess the question is "what is NM being used for?" (I don't know...we don't use it!) 

If its being used for **data-quality**, then I agree that any ambiguous base in the read (non-ACGT) should count towards NM as well as actively mismatching bases (i.e. bases in the read that are not a specific case of the base in the reference.) 
But if NM is used as an indication of a **mismatch** between the read and the reference, then I think that we should only consider actively mismatching bases (as currently in Picard).  

At any case, I don't see why NM needs to be the number of mismatched bases in the MD tag, per se. counts them if you want! they can still be calculated at the same time, even if they are not connected that way.

**Comment by jkbonfield** [comment] 2017-09-06 08:43
Well, I did say "IMO the only odd thing here is N vs N, which to me is a match! Why it's treated as mismatch by samtools calmd is a mystery" so I appreciate the inconsistency exists and was trying to learn why the special case exists.

I cannot answer the question of what NM Is used for.  I'm not sure if we use it anywhere either.

Point taken that it doesn't necessarily have to match MD.  I've always associated the two together as they always get computed together, but you're right that they may have different counting algorithms.  As usual, this is just a problem of the spec being utterly vague!

**Comment by tfenne** [comment] 2017-09-06 12:36
@jkbonfield & @yfarjoun I don't think `NM` is widely used, but it definitely is used.  One good example is VarDict and VarDictJava, a pair of variant callers that are quite popular.  They use the `NM` tag as a quick way to identify reads that have `> n` differences vs. the reference and either discard those reads or classify them as good vs. bad reads.  In that case, I think the calculation one would want would be more "what's the evidence that the read is different than the reference", which to my mind would only count incompatibilities - i.e. not Ns in the read vs. known bases in the reference, and not, e.g. an `A` in the read where there's an `R` in the reference.

I think perhaps it's more useful to calculate only the disagreements (plus gap opens) since even without MD you can look at the cigar for alignment details and the read bases for how many ambiguous bases are in the read.  But it's not a strong opinion!

**Comment by yfarjoun** [comment] 2017-09-06 13:22
Thanks for that @tfenne. Good to get a reminder of the "other" tools out there.... :-)

As a clarification, when you say "disagreement" do you mean "the base in the read is not equal the base in the ref"?

**Comment by tfenne** [comment] 2017-09-06 13:27
I was thinking more "the base in the read is not compatible with the base in the ref".  By which I think I mean a bi-directional comparison that allows for ambiguity on either side so long as there is at least one base in the intersection!

**Comment by yfarjoun** [comment] 2017-09-06 13:42
By this logic, an N base (in either read or ref) will never increase NM. That's not what I was thinking, but it has some rational foundation as in:

We assume that both the TRUE reference and the reads (an unknown) are ACGT bases, whilst the "measured" REF and SEQ may have ambiguous bases that are compatible with the truth. We increase NM when there is evidence for a mismatch between the the TRUE ref and read.

**Comment by yfarjoun** [comment] 2017-09-06 13:51
here's the compatibility table that I think you are implying:


READ | REF | NM| comment
----|----|----|----
R | R | 0
R | A | 0
A | R | 0
A | A | 0
N | N | 0
A | G | 1
K | M | 1|  (M=A\|C) , K=(G\|T)
K | R  | 0| (R=A\|G)

**Comment by tfenne** [comment] 2017-09-06 14:21
@yfarjoun Exactly.  I think that makes sense.  I'm not wedded to it, and it's certainly a more complicated implementation, but I think it is probably the most useful.  Perhaps when we decide and update the spec it should be the "recommended implementation" or at least acknowledge that it was underspecified at the time and not everyone will calculate it the right way.

**Comment by jkbonfield** [comment] 2017-09-21 16:39
I'll make a PR in hts-specs on this later, but I'll add a quick comment after the conference call.

MD is clearly the tag more appropriate for variant calling, as it permits calling without a reference.  That means NM probably has little benefit with regards to variant analysis.

Heng's original implementation was N==N counts up by 1.  In a strict sense of base-calling we are trying to determine A, C, G or T, and N is basically incorrect (non-call), so I can hand-wavingly guess at where this specific logic came from.

If we interpret NM as strictly a base-calling QC thing then we want to know how many bases are incorrect (or SNP), if we assume the mapping to be correct.  In that regard, any ambiguity code in seq is NM+1 (even R, N, etc).  Thus call-QC would use something like

READ | REF | NM| comment
----|----|----|----
A | A | 0
A | G | 1
A | R | 0 | A/G
A | N | 0
R | A | 1
R | G | 1
R | R | 1
R | N | 1
N | N | 1

This is asymmetric and doesn't really match the specification, but it's rather ambiguously written so who knows.

If we interpret NM as a mapping-QC to know how compatible the sequence alignment is, then we get the table @yfarjoun shows above. 

Do we know of any sequencing instruments that produce ambiguity codes in their sequence, other than N? If not then the two tables are basically identical except for N|N. They are permitted in the reads though so we need to figure out what to do if they occur.

It was also pointed out (sorry I forget by whom) that the SA tag refers to NM, but checking this is doesn't elaborate any more other than to state the value is present in that field.

**Comment by jdidion** [comment] 2018-03-22 17:17
Is there any update on this? This issue is blocking our team from moving from CRAM to BAM - it's a no-go unless a BAM file converted to CRAM and then back to BAM is identical to the original BAM (except for tag ordering).

What about adding an option that allows the user to choose whether to treat N<->N as a match or mismatch for the purposes of computing NM and MD tags?

**Comment by jkbonfield** [comment] 2018-03-23 15:35
Sorry for not working on this sooner.

There is a simple work around which we can put in place quickly hopefully (Io_lib's Scramble already has it).  By storing NM and MD verbatim *always*, they will be round tripped correctly.  It makes the CRAMs bigger, but it's a trivial way of preventing this from being a problem while we put the more complex logic in place to detect when a round-trip would fail.

**Comment by jkbonfield** [comment] 2018-03-23 17:38
I've hopefully solved this issue in two ways.

1) The cram encoder in htslib now specifically looks for the contentious N vs N case and stores NM/MD verbatim in this scenario, to ensure preservation of any existing tools.

2) There are now options to store *all* NM and MD verbatim, which should be used in conjunction with the decode_md=0 option when decoding.  This means a round-trip will never add NM and MD to existing records if they didn't have them originally, meaning that samtools output should be accepted by Picard irrespective of whether there is N vs N anywhere.

**Comment by jkbonfield** [comment] 2018-03-26 11:21
Fixed in https://github.com/samtools/htslib/commit/a5dc7e00543219580859454c94ee237653950517, but the spec issue of lack of clarity in NM definition remains.

See https://github.com/samtools/hts-specs/issues/177 for spec issue, although it needs resurrecting.

**Closed by jkbonfield** 2018-03-26 11:21 UTC
