### ISSUE TITLE
samtools cram conversion results in different insert size sd

### ISSUE THREAD

**Issue by sb10** [samtools/samtools#340] opened 2015-01-28 10:18 UTC
If I convert a bam to cram with samtools 1.1 (using htslib 1.1), samtools stats gives a different insert size standard deviation.

cd /lustre/scratch107/user/sb10/samtools
samtools view -C -T Mus_musculus.GRCm38.68.dna.toplevel.fa issd.bam -o issd.bam.cram
samtools view -b issd.bam.cram > issd.bam.cram.bam
samtools stats issd.bam > issd.bam.stats
samtools stats issd.bam.cram > issd.bam.cram.stats
samtools stats issd.bam.cram.bam > issd.bam.cram.bam.stats
diff issd.bam.stats issd.bam.cram.stats | grep SN
  SN    insert size standard deviation: 82.3
  SN    insert size standard deviation: 82.2
diff issd.bam.cram.stats issd.bam.cram.bam.stats | grep SN
[no diff]

**Comment by jkbonfield** [comment] 2015-01-28 11:06
Please see the https://github.com/samtools/htslib/tree/cram_tlen_fix branch.

We'll be merging this in very soon and making a new release, but I will validate it against your BAM file to double check.

**Comment by jmarshall** [comment] 2015-01-30 13:08
This is merged now.  Would you be able to retest your stats with current **develop**?

**Comment by jmarshall** [comment] 2015-07-06 13:58
No further reply, so hopefully the problem is addressed :smile:

**Closed by jmarshall** 2015-07-06 13:58 UTC
