### ISSUE TITLE
samtools 1.10 incompatibility with @RG header section

### ISSUE THREAD

**Issue by DrQuestion** [samtools/samtools#1237] opened 2020-05-04 17:25 UTC
Hello,
I'm experiencing some troubles in using samtools 1.10. 
My OS is Linux 4.4.0-18362-Microsoft, machine architecture x86_64, gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0.
I've been given a bam file by my professor, but even when running a simple view:
`samtools view Sample.bam`
It outputs an error:
`[E::sam_hrecs_error] Malformed key:value pair at line 86: "@RG  ID:A18  PL:Illumina     LNID:5  FCID:HHH7NBBXX  DT:2017-01-10T00:00:00+0100       BCID:GTCCGC     SM:A18-germline"`
`samtools view: failed to add PG line to the header`
I wonder what's wrong with the RG line of the header, and simply removing it is something to avoid, I think.

**Comment by mp15** [comment] 2020-05-04 17:48
Two interesting things about that header. Firstly could you check for me are those spaces or tabs in your @RG line. It’s also using some interesting non-standard 4 character tags. I hope these won’t trip up the header parser but they might. Try adding ‘—no-pg’ to your command line.

**Comment by valeriuo** [comment] 2020-05-05 11:19
Unfortunately, `--no-PG` won’t help in this case, as the header is still being parsed and the error generated upon encountering the illegal tag keys. The tags have to be corrected or removed.

**Comment by DrQuestion** [comment] 2020-05-05 12:03
Thank you for your answers!
Using `--no-PG` solves the problem only for viewing, but more complex actions as sorting result in the same issue.
If I can add an additional piece of information, which I found interesting: I know that previous versions of samtools, up to version 1.9, experience no problem at all.

**Comment by valeriuo** [comment] 2020-05-05 12:46
A new header parser was added in 1.10, which does a better job at enforcing the SAM standard, at the expense of not working with malformed files.

**Comment by daviesrob** [comment] 2020-05-05 15:56
Closing as caused by bad input.  Please ask your professor to fix his file.

**Closed by daviesrob** 2020-05-05 15:56 UTC

**Comment by lacek** [comment] 2020-10-20 06:14
Is it possible to add a fallback option to only warn the malformed header and process anyway?

We've got thousands of BAM files generated by legacy pipelines that can no longer be viewed with newer versions of samtools. We now run in a difficult situation that:

1. If we reheader the BAM files, it would take numerous computational hours.
2. If we stay on using older versions, we cannot access new features and bug fixes.
3. If we mix the use of  new and old version of samtools, it may confuse the users and make related scripts/tools complicated

It would be nice to have a compatibility option (at least for the view command) if possible.

**Comment by jkbonfield** [comment] 2020-10-20 08:24
Reheader is very compute light as once it's replaced the header it ought to be little more than a read/write loop unless some major header things have changed.  Wanting the software to gloss over invalid data is just saving up gotchas for a later day and IMO not the thing to do.

If you really do wish to do this, then your only option is to stick with old versions of software (not just ours, but the entire processing stack), but I'd strongly advise against that.

**Comment by daviesrob** [comment] 2020-10-20 09:30
What do the bad header lines look like and what produced them?

`samtools reheader` is the best way to fix them at the moment.  It now has a `-c` option that allows you to pass the old header through a filter, so the one mentioned above can be fixed with something like this:

```
samtools reheader -c "perl -lne '@F = split(qq[ ], \$_); foreach \$i (@F) { \$i =~ s/^(..)ID:/\$1:/; } print join(qq[\\t], @F);'" bad.bam > good.bam
```

After replacing the header it essentially does a `cat` of the rest of the file, so it's very fast.

We might be able to add a work-around to drop bad tags, but that's always going to be more error-prone and potentially lossy compared with fixing them properly with reheader.

**Comment by lacek** [comment] 2020-10-20 11:27
The BAM files with bad header are produced from various old in-house pipelines. They contain @RG header with a single extra tab character at the end of the line. It can be fixed by reheader using `-c` options along with a simple `sed` command.

Although the reheader command is mostly I/O operation, extra processing time are required as we have to reindex the fixed BAM files to provide random access to other applications. With the environment I have now, the estimated processing time is around 15 hours per TB of data. To migrate all of old BAM files with the bad header, it would take us half a month of processing time on a single server, given the rate sustains and nothing goes wrong.

So in this case, I think I'll stick to the old version until we figure out a good migration plan then.

Thanks for the suggestion and nice work anyway.
