### ISSUE TITLE
the step of samtools mpileup is very slow

### ISSUE THREAD

**Issue by caixu0518** [samtools/samtools#945] opened 2018-09-08 14:54 UTC
Hello developers,

I have been running the step of **samtools mpileup** for several days to get whole genome variations, beacuase of large genome and big sorted bam. I want to know if this step can support mult-ithreads? Or can you show me some quick way to get the results of this step?

Best regards,
Xu Cai

**Comment by valeriuo** [comment] 2019-09-27 09:04
Duplicate of #480

**Closed by valeriuo** 2019-09-27 09:04 UTC
