### ISSUE TITLE
SO: field options in header

### ISSUE THREAD

**Issue by dcopetti** [samtools/samtools#811] opened 2018-03-28 09:26 UTC
Hello,
I am reheading a large (180 GB) bam file and I would like to specify the correct SO tag in the head.
The bam was produced as follows:
```
samtools view -@4 -h -b -F4 parsed_aln0.bam >parsed_aln0_F4.bam
samtools merge -@8 -tBX -b bams_list - | samtools sort -@8 -tBX -o genome.reads.sortbx.bam
samtools index genome.reads.sortbx.bam
[E::hts_idx_push] Chromosome blocks not continuous
samtools index: failed to create index for "genome.reads.sortbx.bam
```
(I guess I lost my header at the merge step).
So I produced a header from the reference that looks like this:
```
@HD     VN:1.5  SO:unknown
@SQ     SN:scaffold1    LN:5156610
@SQ     SN:scaffold2    LN:17605516
@SQ     SN:scaffold3    LN:111845
@SQ     SN:scaffold4    LN:4519529
@SQ     SN:scaffold5    LN:1475893
```
but the sort step gives me the same problem:
```
samtools index genome.reads.sortbxhead.bam
[E::hts_idx_push] Chromosome blocks not continuous
samtools index: failed to create index for "genome.reads.sortbxhead.bam"
```
I guess since the file is sorted according to the BX tag. What is the right string to put for SO in my case?
Thanks,

Dario

**Comment by dcopetti** [comment] 2018-03-28 11:04
I am OK with the unknown string, but looking at the code of the software I am running (tigmint-span, developed by @sjackman ) the indexing step will happen anyway: 
```
# Index a BAM file.
%.bam.bai: %.bam
       samtools index $<
```
I am doing this step external from tigmint because of [this](https://github.com/bcgsc/tigmint/issues/8) issue. 

Furthermore, if I look at the output from the reheader step
```
samtools reheader head genome.reads.sortbx.bam >genome.reads.sortbxhead.bam
samtools view genome.reads.sortbxhead.bam | more
```
the first line I see is the alignment:
```
ST-E00273:278:HGCTHALXX:7:2115:10642:64404      163     scaffold1       83      0       151M    =       172     217     GATGTATTTGGTTCTAGAAATGAGCCAAGTTGTATTTTACACACAATAATTTTATCTCCCACACATTTGCAAAGATGTGTTTGTAGAAAGTAAATTGTTAC
TTTACACATGTACTAAGTTGCATACCCATTATCTCTAAGTTGTATACCCC      AAFAFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJFFJFJFFFJJJJJJFJJJFJFJJJJJF<<FAAAA<F<FAFJ<F7FA<A7<7FFF-7< NM:i:0  MD:Z:
151     MC:Z:128M       AS:i:151        XS:i:151        XA:Z:scaffold195870,+318,151M,0;scaffold2768,+156503,151M,0;scaffold185,+964390,151M,2;scaffold2297,-4073628,83M1D68M,5;
```
Is it normal not to see the header or did something go wrong? I did not get any error line after the reheader step.
Thanks

**Comment by jkbonfield** [comment] 2018-03-28 11:46
Use samtools view -h file.bam to show the header.   By default it is not displayed.

**Comment by sjackman** [comment] 2018-03-28 18:36
Tigmint does not need to index the barcode-sorted BAM file, since it's not possible to index a barcode-sorted BAM file. It's a bug if `tigmint-make` is trying to create such an index, in which case open an issue at https://github.com/bcgsc/tigmint/issues/new

**Comment by sjackman** [comment] 2018-03-28 18:39
@jkbonfield A bit off topic, but I do have occasion where I'd like to index a barcode-sorted BAM file, so that I can extract all the alignment of a particular barcode using `samtools view foo.bam BX`. It could be possible if the index were created on (BX, POS) rather than the typical (RNAME, POS). There is in fact a tool for this purpose, that replaces RNAME with BX and moves RNAME to a tag, so that the resulting BAM file can be indexed with `samtools index`. See https://github.com/walaj/bxtools#convert

**Comment by jkbonfield** [comment] 2018-03-28 19:38
It's certainly possible to create your own index on anything, although it's a bit misleading to be doing this via the standard indexing machinery as it's no longer a reference coordinate index which is what our tools support.

Faking it up is probably the best we can do, and that's a high level hack you have there. :-)

**Comment by jkbonfield** [comment] 2018-04-03 15:50
I'm closing this as I think it's a samtools issue per-se, but a SAM spec deficiency.  If you have any comments on handling new sort order definitions please comment in https://github.com/samtools/hts-specs/pull/221

Regarding newer indexing methods, these could be done but aren't on our agenda unless we see sufficient need.  (If so someone can champion the cause and raise a new more appropriately titled issue.)

**Closed by jkbonfield** 2018-04-03 15:50 UTC

**Comment by jkbonfield** [comment] 2018-04-04 08:44
Ooops, I meant to say it's NOT a samtools issue.   Apologies for the confusion.

**Comment by adc0032** [comment] 2020-05-11 18:31
Just to be clear, indexing a BAM that has been sorted by -BX tag is not possible, due to it being out of the purview of samtools? Just checking to see if anyone had offered or devised a way to work around this! Thank you!

**Comment by sjackman** [comment] 2020-05-11 19:08
Not out of the box, Amanda, but you can hack it up and make it work by putting the `BX` tag in the target/chromosome name (column 3 of the BAM file). It's not super performant, but it works.
See https://github.com/sjackman/talr/blob/master/bin/index_barcodes.py
and https://github.com/sjackman/talr/blob/master/bin/get_barcode_reads.py

also https://github.com/walaj/bxtools#convert

and https://github.com/johandahlberg/awesome-10x-genomics#linked-reads
