### ISSUE TITLE
Combining -L and -X options on samtools view -c

### ISSUE THREAD

**Issue by franrodalg** [samtools/samtools#1720] opened 2022-09-18 13:25 UTC
Hi everyone,

I'm attempting to obtain the total number of reads aligned to a handful of regions using a bed file (i.e., option `-L <filename>`). On the cloud computing environment I need to run this I have to explicitly specify the location of the index file or it cannot be found automatically (even if the cram and crai files are located alongside each other), so I need to include the option `-X <cram> <crai>` or suffer an unworkable computing length while the alignments are indexed.

Unfortunately, even though computation was working perfectly well when I was indicating a single region of interest (i.e., `samtools view -c -X <cram> <crai> <region>`), I receive an error if I try to replace the region with a path to the bed file, no matter whether I include `-L` before (i.e., `samtools view -c -L <bed> -X <cram> <crai>`) or after (i.e., `samtools view -c -X <cram> <crai> -L <bed>`) `-X`. In particular, I get the following error message:

`samtools view: Incorrect number of arguments for -X option. Aborting.`

Loaded versions of samtools and htslib are both 1.15.1.

Am I missing something? Are these two options somehow incompatible?

Any help would be greatly appreciated.

Cheers,
Fran

**Comment by jkbonfield** [comment] 2022-09-20 08:13
> On the cloud computing environment I need to run this I have to explicitly specify the location of the index file or it cannot be found automatically (even if the cram and crai files are located alongside each other), so I need to include the option `-X <cram> <crai>` or suffer an unworkable computing length while the alignments are indexed.

I think this is the first problem to solve.  I suspect everything else stems from some index loading failure.

Why isn't it automatically finding the index?  When you say "cloud computing environment", do you mean samtools is running in the cloud with the files presented locally to it (which therefore should look much like a non-cloud environment to samtools), or that the data files are in the cloud while the samtools compute is somewhere else (possibly a different cloud machine or a local one), so you're using s3:, https:, gcs:. etc URIs to fetch the data?  If we have a failure fetching the CRAM indices via cloud services then this is something we need to fix (although I thought we already had).

> Unfortunately, even though computation was working perfectly well when I was indicating a single region of interest (i.e., `samtools view -c -X <cram> <crai> <region>`), I receive an error if I try to replace the region with a path to the bed file, no matter whether I include `-L` before (i.e., `samtools view -c -L <bed> -X <cram> <crai>`) or after (i.e., `samtools view -c -X <cram> <crai> -L <bed>`) `-X`. In particular, I get the following error message:

The `-X` semantics are pretty clunky, but they got added after the rest of the CLI was designed so it had to be shoe-horned in somehow.  I can't see why it would be incompatible with -L though.  It certainly works for me locally, so this is something cloud related.

Also, what OS is this?  I'm aware that getopt can differ between platforms as to how options after non-options (eg filenames) work.

**Comment by franrodalg** [comment] 2022-09-20 09:40
Thanks for your reply, James.

Unfortunately, I have very little information about the platform itself. I am using the UK Biobank Research Analysis Platform, which is run by DNANexus, and the documentation is fairly limited. I have requested information about the OS that their computing servers employ, since not even that is easily available (as far as I know). 

All command line interaction is done through their own tool, so I don't even have access to most basic commands, such as `uname`.

Regarding why the index is not accessible unless using `-X`, their data and computing nodes are apparently not readily connected. The supposed default method to access data is to "download" all files of interest to the computing nodes first, and then initiate the execution of whatever command the user has requested. In this case, we are talking about 200,000+ cram files of >30GB each, which makes the download overhead a no-go for us (since we are being charged for computation time). 

The alternative is what they call a "streaming" mode, which is currently in beta. In theory, we can access the files as if they were located within the computing node using what I assume is a symlink. The main issue with that is that specifying the "virtual" path for the alignment file doesn't seem enough for samtools to locate the corresponding index file on an equivalent path. In particular, the actual paths in the data storage are prepended with `/mnt/project/` in the submission scripts, and I assume these are converted into whatever true path is necessary to reach them from the computing nodes (e.g., converting "project" into our particular project ID that enables the platform to associate the execution with "our" data). I suppose samtools cannot internally do whatever conversion their platform is doing, and thus cannot find the path to the index.

I'm sorry if this is too convoluted. I honestly can't understand why they don't use a normal HPC architecture. It took me forever to make anything work in the first place.

Anyway, I hope this helps. I will update as soon as I know the OS version. 

In the meantime, I have been running samtools -c separately for each region of interest and later summing the results, but I assume it is much more efficient to do so on a single call with -L.

**Comment by jkbonfield** [comment] 2022-09-20 14:19
If it's a cloud set up I imagine it's some linux derived thing so OS probably doesn't matter too much.  I was just thinking about a local executable on e.g. a Mac using a cloud for file stores.

For efficiency, `-L` may just be streaming, although if I recall we make it use an index too so with `-M`.  Without it though it's likely to be very slow and unless your regions are very tightly clustered it won't be any faster than separate commands with single regions.

Also note that -X was designed for commands that take many filenames (eg `merge`).  While it works on single files, it may be easier to use the rather arcane */data/in.bam##idx##/indices/in.bam.bai* syntax (search for ##idx) in the samtools.1 man page for details.  This allows it to be specified as a single filename.

I'm afraid I probably can't help much more than that.  If you have it working locally with your command but not within the DNANexus environment, then I'd advise raising a support ticket with them as they will know far more than us about whatever their internals are doing.  However if you get an error running on local files, then we'd gladly take a look at that.

**Comment by jkbonfield** [comment] 2022-10-04 13:28
I'm unable to reproduce this and no replies, so closing.

**Closed** 2022-10-04 13:28 UTC

**Comment by franrodalg** [comment] 2022-10-04 13:42
Hi James,

Sorry for taking so long. I needed a result quickly so I ended running it with multiple separate calls.

The number of regions to check has now increased, so I am actually running a job currently with your `##idx##` suggestion, but given how long it is taking to complete a single sample (>20 min so far, compared to the few seconds it takes when I can use -X) I have the feeling it isn't working. Is there any way to know if the index has been properly loaded?

Cheers,
Fran

**Comment by franrodalg** [comment] 2022-10-05 13:39
HI James,

A couple of notes. 

We have managed to avoid the error when including -L and -X simultaneously if we use an older version of the environment. I have just checked and the samtools version loaded in such older environment appears to be 1.11, in case that helps.

That being said, I have noticed that using -L instead of explicitly indicating a position takes up to an order of magnitude longer. This doesn't seem to depend on whether -X is included or not. Is that to be expected? Is there a number of positions/regions for which using a bed file might start being more efficient than several separate calls with posterior merging?

Cheers,
Fran

**Comment by jkbonfield** [comment] 2022-10-05 14:21
That does sound like it's not using an index and is just streaming instead.  Does adding a -M option change this?

There's no direct way for samtools to report if it's using an index, but `strace -f samtools view ... 2> strace.out` will show what's going on.  Do something small, or start it and let it run for a few seconds before killing it.  Then you can grep through the output to look for the file opens and see what files it accessed.

**Comment by jkbonfield** [comment] 2022-12-14 11:51
Thanks for raising this again.

This is a genuine bug caused by #1542 which appears to have pretty much removed `-X` support.  This is obviously an error and I'm working on a PR to fix this now.  I'm not sure why I was unable to reproduce it earlier.
