### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: Value (70159) to large to be written as ushort.

### ISSUE THREAD

**Issue by dietmar113** [samtools/samtools#2000] opened 2024-03-08 14:25 UTC
hello,

samtools 1.19.2
Linux 4.18.0-513.18.1.el8_9.x86_64
gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-20)

(installed via bioconda in conda environment)

samtools is used by another java program (mirdeep* [ https://sourceforge.net/projects/mirdeepstar/files/?source=navbar ]

Perhaps the genome of the organism is too large? 
Axolotl: ∼32 Gb

the error is:
`Exception in thread "main" java.lang.IllegalArgumentException: Value (70159) to large to be written as ushort.
	at net.sf.samtools.util.BinaryCodec.writeUShort(BinaryCodec.java:324)
	at net.sf.samtools.BAMRecordCodec.encode(BAMRecordCodec.java:128)
	at net.sf.samtools.BAMRecordCodec.encode(BAMRecordCodec.java:37)
	at net.sf.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:210)
	at net.sf.samtools.util.SortingCollection.add(SortingCollection.java:150)
	at net.sf.samtools.SAMFileWriterImpl.addAlignment(SAMFileWriterImpl.java:179)
	at miRDeep.mapping_identifying.alignment(mapping_identifying.java:551)
	at miRDeep.mapping_identifying.mapping_identifying_proc(mapping_identifying.java:139)
	at miRDeep.miRDeep_command_line.main(miRDeep_command_line.java:106)
`

**Comment by jkbonfield** [comment] 2024-03-08 14:51
I suggest you report this to the authors of the Java program.  Samtools is pure C and cannot produce a Java exception itself, so this is coming from whatever tool is driving samtools.  It's likely somewhere in htsjdk, but that doesn't mean that is responsible either as it could be the calling code.

Closing as the problem is for another package.

**Closed by jkbonfield** 2024-03-08 14:51 UTC
