### ISSUE TITLE
[E::sam_parse1] query name too long + error reading file "-"

### ISSUE THREAD

**Issue by tamuanand** [samtools/samtools#1932] opened 2023-10-23 14:22 UTC
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib]
**yes
samtools 1.18**

 #### Please describe your environment.
- OS Linux **4.14.314-237.533.amzn2.x86_64**
- machine architecture **x86_64**
- compiler gcc **(Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0**

I am running this using docker on AWS EC2 g4dn.12xlarge
- 4gpus, 48cpus, 192 GB RAM

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

I am trying to break down a huge bam file so that each file has 50M lines and then run bwakit on the split files as below 
- 130GB fastq file broken down into 22 smaller files 

```
    samtools view -H "${sample_id}.bam" > header

    samtools view "${sample_id}.bam" | split -l 50000000 - split_bam_

    time ls split_bam_* \\
        | parallel -j 4 "/usr/local/bin/k8 /usr/local/bin/bwa-postalt.js ref.alt {}" \\
        | cat header - \\
        | samtools view --fast --threads 4 -o "${sample_id}.postalt.bam"

```

I keep getting this error (90% of the times) 

```
[E::sam_parse1] query name too long
samtools view: error reading file "-": Input/output error
samtools view: error closing "-": -5
```

and in 10% of the times I get something like 

```
[E::sam_parse1] CIGAR and query sequence are of different length
samtools view: error reading file "-": Input/output error
samtools view: error closing "-": -5

OR 

[E::sam_parse1] SEQ and QUAL are of different length
samtools view: error reading file "-": Input/output error
samtools view: error closing "-": -5
```

Is there something I can do differently here?

Thanks in advance.

**Comment by jkbonfield** [comment] 2023-10-24 08:24
I'm wondering if we ought to create a `samtools parallel` command to aid such things.  Converting to SAM and using split feels like a horribly inefficient process.

Generally people archieve this sort of parallelism using regions.  Does bwa-postalt.js  not have a region option?  Unfortunate if not.

As for this specific error, generally it's preferable to break a pipeline down to something which writes to a file, so you can visually inspect the lines it complains about.  Eg in your case you could do:

```
time (cat header; ls split_bam_* \\
        | parallel -j 4 "/usr/local/bin/k8 /usr/local/bin/bwa-postalt.js ref.alt {}") > debug.sam
```

This will then allow you to run `samtools view ...`  on the file and look at the line numbers it fails on, or use head and tail combinations to gradually isolate it down to a specific few lines that are problematic, so you can inspect them.

However I expect the problem is just one of mixing multiple streams together.  You have 4 tasks running simultaneously all writing to stdout, and you're expecting them not to clash and to always be line by line oriented.  That's highly unlikely to be true.

If you have a need for bwakit to be multithreaded, I suggest you ask the bwakit author for advice on multithreading, or use biostars for wider community support.  This isn't a samtools issue.

**Comment by jkbonfield** [comment] 2023-10-24 08:36
Closing as I found this also cross-posted to https://www.biostars.org/p/9578282/, where I've added another comment.

Please refrain from posting the same questions to multiple places (although BioStars is definitely a better place for general bioinformatics pipeline questions than here).

**Closed by jkbonfield** 2023-10-24 08:36 UTC

**Comment by tamuanand** [comment] 2023-10-24 13:35
@jkbonfield this is not a cross posting 

please look carefully before suggesting that this is a cross post.

In biostars I asked about samtools view fast .... here I am giving the errors I got

**Comment by tamuanand** [comment] 2023-10-25 18:53
Hi @jkbonfield 

Wanted to pass this by you before trying it out

My original workflow (causing the issues I reported and hence this discussion topic)

```
Step 1  - WGS fastqs as input - Use Parabricks pbrun fq2bam in align-only mode to get a bam

Step 2 - samtools view/split/parallel  followed by bwakit and then samtools view as shown above

Step 3 - use the merged bams as input for downstream Parabricks processing
```

Would it be better to do something like this below?

```
Step 1  - WGS fastqs as input - Use Parabricks pbrun fq2bam in align-only mode to get a bam

Step 2 - samtools collate or samtools sort -n 

Step 3 - Use https://gatk.broadinstitute.org/hc/en-us/articles/13832693663899-SplitSamByNumberOfReads-Picard- (this requires query name sorted bam files) to split into smaller bam files

Step 4 - convert these small bams to sams and do bwakit processing

Step 5 - take all the bams and then do samtools cat or merge

Step 6 - use the merged bams as input for downstream Parabricks processing
```

Some specific questions where I would like to seek your guidance

1. Would you recommend samtools sort -n or samtools collate for Step 2 above - also happened to see your tips here: https://github.com/samtools/samtools/issues/1834
2. Should I use `samtools cat` or `samtools merge` - in [here](https://www.biostars.org/p/9578282/#9578408)  you seem to suggest `samtools cat`

Thanks in advance.

**Comment by tamuanand** [comment] 2023-10-26 14:13
Thanks @jkbonfield for all your inputs. AFAIK `bwakit` [is from @lh3](https://github.com/lh3/bwa/blob/master/bwakit/README.md) - am I correct? 

One final question on this topic - is there any guidance on how to speed up `samtools collate` 
- does increasing `--threads` help - is there a good number also keeping in mind law of diminishing returns
- does increasing `-n` (number of temporary files help)
- will using `-u` help 

`SplitSamByNumberOfReads` is expecting a bam file that works with something like `samtools collate` but does not work with bam files coming from `samtools sort -n`

I have a 130GB bam file 
- r6i.8xlarge - 32cpus, 256GB ram
- `samtools collate --threads 12 -T tmp_ -o collated.bam  original.bam` has been running for 3hrs now 
- `samtools view --threads 8 -c original.bam` = 1079445875

Thanks
