### ISSUE TITLE
Inconsistent mpileup results w/ and w/o fasta file

### ISSUE THREAD

**Issue by yjqiu** [samtools/samtools#681] opened 2017-05-13 17:30 UTC
When I run the mpileup command with or without fasta file, the output results are different. Only one mismatch is in the output with fasta file, but two mismatches are reproted without fasta file. I manually checked, and the two mismatched are indeed in the bam file.

Samtools version:

samtools 1.3
Using htslib 1.3
Copyright (C) 2015 Genome Research Ltd.

Commands I run:

samtools mpileup test.bam -r chr22:23041911-23041911 -f ~/genome/hg19/hg19.fa

Bam file:

SN1113:785:H5M5KBCXY:2:2211:20423:55861	0	chr22	23041867	60	4S46M	*	0	0	ATTAGTGGTCCAAGGATAAACTTTGGGGATATTACCTATGGACTTATAGC	0<<<<DHHIIHHHIHFG1<FHHHIIIIIEHIGFHHIIIIHIHIIIHHIII	MD:Z:13C30T1	PG:Z:MarkDuplicates	RG:Z:JY300-1	NM:i:2	AS:i:39	XS:i:19
SN1113:785:H5M5KBCXY:1:1107:9469:18224	0	chr22	23041885	60	4S46M	*	0	0	CAGATTGGGGAAATTACCTATGGACTTATAGCACCATTTACAATGCAAAC	D00D<C111/E0GHCHIII@1CH?HIHHFHEHHECFHHHIF1<D?FHGH@	MD:Z:7T18T19	PG:Z:MarkDuplicates	RG:Z:JY300-1	NM:i:2	AS:i:36	XS:i:19

**Comment by jkbonfield** [comment] 2017-05-15 14:26
Unless I hear otherwise I will close this soon as a duplicate of various issues (eg https://github.com/samtools/samtools/issues/662, https://github.com/samtools/samtools/issues/79, https://sourceforge.net/p/samtools/mailman/message/35247806/) caused by the BAQ scores.

The BAQ alignment score is beneficial (and hence on by default), but only possible when using a reference which is why you see the difference.   To validate this is the cause I suggest you try using -B to disable BAQ calculation.   Please let me know if this explains the difference.

**Comment by yjqiu** [comment] 2017-05-15 17:49
it solved the problem. Thanks!

**Closed** 2017-05-16 07:56 UTC
