### ISSUE TITLE
"samtools tview" does not support "##idx##" syntax

### ISSUE THREAD

**Issue by cariaso** [samtools/samtools#1587] opened 2022-01-29 23:15 UTC
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? 
samtools 1.11
Using htslib 1.11
Copyright (C) 2020 Genome Research Ltd.

 #### Please describe your environment.
- OS
Linux 5.10.93-87.444.amzn2.aarch64

- machine architecture
aarch64

- compiler
gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-13)

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

somewhat related to https://github.com/samtools/samtools/issues/1541

This command works
`samtools view -H "s3://privatebucket123/path/to/afile.cram##idx##s3://privatebucket123/other/path/afile.cram.crai"`

but the somewhat equivalent tview does not work 
`samtools tview -d h -p chr16:69711232 "s3://privatebucket123/path/to/afile.cram##idx##s3://privatebucket123/other/path/afile.cram.crai" /reference/Homo_sapiens_assembly38.fasta`

it fails with the message

```[E::cram_index_load] Could not retrieve index file for 's3://privatebucket123/path/to/afile.cram##idx##s3://privatebucket123/other/path/afile.cram.crai'
samtools tview: cannot read index for 's3://privatebucket123/path/to/afile.cram##idx##s3://privatebucket123/other/path/afile.cram.crai'
```

copying the files to a local disk, and then running equivalent commands reveals that

it does not work when the files are in different subdirectories
`samtools tview -d h -p chr16:69711232 "sub1/afile.cram##idx##sub2/somename.crai" `

```
[E::cram_index_load] Could not retrieve index file for 'sub1/afile.cram##idx##sub2/somename.crai'
samtools tview: cannot read index for "sub1/afile.cram##idx##sub2/somename.crai"
```

although other parts of samtools do work with this syntax
`samtools view -H "sub1/afile.cram##idx##sub2/somename.crai"`

tview works only with the non ##idx## form
`samtools tview -d h -p chr16:69711232 sub1/afile.cram`

and fails on the equivalent
`samtools tview -d h -p chr16:69711232 "sub1/afile.cram##idx##sub1/afile.cram.crai"`

**Comment by jkbonfield** [comment] 2022-02-01 09:38
I can't reproduce this with current develop branch:

```
$ cp data/novaseq.10m.cram /tmp/_x
$ cp data/novaseq.10m.cram.crai /tmp/_y 
$ samtools tview -p 1:33333 /tmp/_x##idx##/tmp/_y
[ working output ]
```

However my 1.14 binary does fail.
Checking out earlier tags also works, which probably implies it's a fix in htslib.  I'll investigate further.

**Comment by jkbonfield** [comment] 2022-02-01 09:42
Ah yes - I managed to forget this!

https://github.com/samtools/htslib/commit/f1ac6bbdc2bf44c0464ceed2f9aa1675bb1dcbfe fixed `##idx##` with CRAM.

That was added post 1.14 release.   The patch is tiny so if you depend on this feature I would recommend manually applying it to the htslib source and rebuilding.  (A new release should be available in the next few weeks.)

**Comment by jkbonfield** [comment] 2022-02-08 15:18
Closing as we believe the issue to be resolved.

**Closed by jkbonfield** 2022-02-08 15:18 UTC
